### ISSUE TITLE
怎样转换范型

### ISSUE THREAD

**Issue by dyfeelme** [x-stream/xstream#100]
请问如何转换如下代码：

//子类如下
public class Foo extends ResponseBody{
 public String extra;

}

//父类如下
public  class Response<T extends ResponseBody> implements Serializable {

  public Response(){}

  private String name;

  private T obj;

//..省略getter,setter

}

//客户端类
public <T extends ResponseBody> Response<T> request() throws Exception {

        XStream xStream = new XStream();
        //...省略
        Response<T> response = (Response<T>) xStream.fromXML(responseXml);

        return response;
    }
//测试代码
Response<Foo> response = client.request();

转换后response.obj中extra为null

**Comment by joehni** [comment]
Tut mir leid, aber ich habe leider keinerlei Ahnung, was Du versuchst, mir Da zu erzählen.

**Comment by joehni** [comment]
Question unknown, no further info provided.
