### ISSUE TITLE
two class, can't have same alias?

### ISSUE THREAD

**Issue by HelloWangmh** [x-stream/xstream#102]
one class :
@XStreamAlias("Image")
public class Image {
}

the other class :
@XStreamAlias("Image")
public class HotelListImage {
}

when i prepare to turn  xml to obj:
 @XStreamAlias("Images")
    ` private List<Image> images;`

the result is :
xstream find HotelListImage   not Image...

**Comment by joehni** [comment]
An alias definition is a mapping between a name ans a class. You're free to define something else than a 1:1 mapping, with the result that either serialization or deserialization is ambiguous. The latest registration wins, but with annotations, you have only limited control over the processing order of the annotations.

**Comment by joehni** [comment]
No further info
