### ISSUE TITLE
annotation tips and use generic problems 

### ISSUE THREAD

**Issue by MichaelChan90** [x-stream/xstream#110]
1、 When I used XStream，I ran into a problem：A Object contains numbers of feilds，but sometimes I want ony a part of them to make up an XML. I need an annotation with "if" or others to help me to package an XML.
2、When I used java generic Entity as an interface to assembly message , it hard to convert XML into the real beans.

example:
今天在做XMl转为Bean的实例，遇到一个奇怪的问题，出代码先：
//工具类：
@SuppressWarnings("unchecked")
public  Object   readXml2Bean(String xml,Class rootClazz,Class headClazz,Class detailClazz){
try {
  xstream.alias("Root",rootClazz);
  xstream.alias("Head",headClazz);
  xstream.alias("Detail",detailClazz);
  return xstream.fromXML(xml);
}catch (Exception e) {
  e.printStackTrace();
  return null;
  }
}
//Head节点用泛型
public class PackRoot<T,M> {
  private T Head;
  public List<M> Detail_List;
  //getter/setter方法略
}
//Head节点用具体类型声明
public class PackRoot<M> {
  private PackHead Head;
  public List<M> Detail_List;
  //getter/setter方法略
}
//测试用例：
File file =new File("D:\\2001.xml");
BufferedReader bf =new BufferedReader(new FileReader(file));
StringBuilder sb=new StringBuilder();
String temp=null;
while((temp=bf.readLine())!=null){
sb.append(temp);
}
Object root=XMl2BeanUtil.getInstance().readXml2Bean(sb.toString(),PackRoot.class, PackHead.class,PackDetail.class);
if(root==null){
  System.out.println("解析报文出错[xml]="+sb.toString());
}
PackRoot<PackHead,PackDetail> rt=(PackRoot<PackHead,PackDetail>)root;
PackHead  head=rt.getHead();
List<PackDetail> details=rt.getDetail_List();
System.out.println("head="+head);
System.out.println("details="+details);
for(PackDetail detail:details){
System.out.println(detail);
}
报文结构：
<Root>
<Head>
   ......
</Head>
<Detail_List>
   <Detail>
     ......
   </Detail>
   <Detail>
     ......
   </Detail>
</Detail_List>
</Root>

**Comment by joehni** [comment]
Hi,

it is [documented](http://x-stream.github.io/manual-tweaking-output.html#Configuration_OmitField), how to omit fields.

I am not sure, what you try to tell me with the second part of your question, but you should never try to configure XStream until it can read some kind of XML format. Always do it the other way round. Configure XStream until it can write the desired format, then it will normally be able to read it also.
