### ISSUE TITLE
XStream 1.4.9/1.4.8 contain JDK 1.8 code (LambdaMapper)

### ISSUE THREAD

**Issue by khmarbaise** [x-stream/xstream#113]
The usage of XStream version 1.4.9/1.4.8 do not work with JDK 7 cause they contain a class which is already compiled with JDK 8...Unfortunately the release notes do not give a hint about that? (Maybe I oversight something).

**Comment by joehni** [comment]
XStream 1.4.x can even run on a Java 1.4 runtime. It will only use (load) what the runtime is capable to run. XStream has a long history of including class files targeting different Java versions.

**Comment by khmarbaise** [comment]
Hm..I think I have expressed not correctly. The byte code checker gives me the hint that classes contained which are JDK 8 compiled etc. so far so ok...but unfortunately I haven't found a hint in the Release notes after I explicitly excluded them it works.

**Comment by joehni** [comment]
OK, fine. Well, the LambdaMapper was added with XStream 1.4.8. ;-)
