### ISSUE TITLE
Dom4jDriver and charset

### ISSUE THREAD

**Issue by wagnergsantos** [x-stream/xstream#115]
Dom4jDriver don't respect charset:

public HierarchicalStreamWriter createWriter(final OutputStream out) {
        Writer writer = null;
        
        if (getOutputFormat() != null)
            writer = new OutputStreamWriter(out, Charset.forName(getOutputFormat().getEncoding()));
        else
            writer = new OutputStreamWriter(out);
        
        return createWriter(writer);
    }

**Comment by joehni** [comment]
Thanks for heads-up.
