### ISSUE TITLE
Standard converters throws NPE when calling canConvert() with 'null' type

### ISSUE THREAD

**Issue by dariusz-michura** [x-stream/xstream#116]
I had to implement my own ConverterLookup which iterates over standard set of converters plus some dedicated ones. I noticed that some of standard converters throws NPE when calling canConvert() with 'null' type. IMHO they should just return 'false' in that case.

Problematic converters:
* com.thoughtworks.xstream.converters.SingleValueConverterWrapper
* com.thoughtworks.xstream.converters.basic.CharConverter
* com.thoughtworks.xstream.converters.collections.BitSetConverter
* com.thoughtworks.xstream.converters.collections.ArrayConverter
* com.thoughtworks.xstream.converters.collections.CharArrayConverter
* com.thoughtworks.xstream.converters.collections.CollectionConverter
* com.thoughtworks.xstream.converters.collections.MapConverter
* com.thoughtworks.xstream.converters.collections.TreeMapConverter
* com.thoughtworks.xstream.converters.collections.TreeSetConverter
* com.thoughtworks.xstream.converters.extended.EncodedByteArrayConverter
* com.thoughtworks.xstream.converters.extended.DynamicProxyConverter
* com.thoughtworks.xstream.converters.extended.JavaMethodConverter
* com.thoughtworks.xstream.converters.extended.JavaFieldConverter
* com.thoughtworks.xstream.converters.extended.FontConverter
* com.thoughtworks.xstream.converters.extended.ColorConverter
* com.thoughtworks.xstream.converters.extended.LookAndFeelConverter
* com.thoughtworks.xstream.converters.extended.GregorianCalendarConverter
* com.thoughtworks.xstream.converters.extended.SubjectConverter
* com.thoughtworks.xstream.converters.extended.ThrowableConverter
* com.thoughtworks.xstream.converters.extended.RegexPatternConverter
* com.thoughtworks.xstream.converters.enums.EnumConverter
* com.thoughtworks.xstream.converters.enums.EnumSetConverter

**Comment by joehni** [comment]
Traditionally the converters never checked for null. However, it does not harm and I added these checks now. There have been more converters though.
