### ISSUE TITLE
Add Configuration to XStream to allow initialization on 'first type encounter'

### ISSUE THREAD

**Issue by Groostav** [x-stream/xstream#12]
Tried posting this to the mailing group, didnt get any kind of delivery failure, I just didn't get it sent to me, and I presume the mailing lists aren't working.

>Hey guys,

>Despite our continued use of XStream we still don't have a comfortable place to do XStream configuration. Theres a hodge-podge of serialization configuration, some of it is trying to avoid a direct dependency on XStream, other parts of it are trying to avoid direct dependencies on other jars inside our own codebase, but all of it isn't nice.

>Well after spending quite a bit of time learning how XStream works in [XSTR-773](http://x-stream.github.io/jira/773/). I was hoping I could convert all of these places to do something like this:

>```Java
class MyModel{
    static{      
        OurSerializerInterface.staticRegistry.addConfiguration(“modeA”, “modeB”, “modeC”);
        //This typically results in a new Converter being registered with XStream
    }
    //…
}
```

>The problem with such a system is that if the first ‘encounter’ with a MyModel is its deserialization, then the converter resulting from the ‘doConfiguration’ call wont be registered in time. When XStream is determining what type is represented by the MyModel node in the XML document, it explicitly doesn't load the type (dodging the converter registration), and its only when the actual unmarshalling occurs, and the sun reflection provider creates an instance of the type, that the static block is called.

>I stepped into the type-locating and converter-finding logic and discovered that the default mapper decides whether or not to initialize the class (ie, call the static block) based on whether or not the nodes name (typically the fully-canonical name of the type being deserialized) starts with a open square bracket.

>What’s the purpose of this code? Can I make a feature request to make it configurable (ie something like xstream.setAlwaysInitializeTypes(true))?

>Cheers,

>-Geoff

**Comment by joehni** [comment]
Hi Geoff,

the list should work now for you ...

Cheers,
Jörg

... slowly working through my emails after vacations ... ;-)

Am Dienstag, 9. Juni 2015, 14:56:33 schrieb Geoff:
