### ISSUE TITLE
JettisonMappedXmlDriver problem

### ISSUE THREAD

**Issue by zyh5160** [x-stream/xstream#126]
When I serialize a java ArrayList using JettisonMappedXmlDriver, calling the deserialization result again returns a nested ArrayList.

`JettisonMappedXmlDriver jsonDriver = new JettisonMappedXmlDriver();
		xStreamJson = new XStream(jsonDriver);
		xStreamJson.setMode(XStream.NO_REFERENCES); `

`	
    
	public void test1() {
		
		List<Bear> dollList = new ArrayList<Bear>();
		
		Bear bear = new Bear();
		bear.getChildren().add(new Bear());
		
		dollList.add(bear);
		
		String s = new String(SerializeUtil.serializeJson(dollList));
			
		Object obj = SerializeUtil.unserializeJson(s.getBytes());
		
		System.out.println("unserialize to json：" + obj);
		
                 // output is : unserialize to json：[[{id:1856098602380990690, name:bear_1856098602380990690}]]
	}`

How to fix this problem, can someone help me?

**Comment by joehni** [comment]
Well, different versions of Jettison create different results. So, which versions of XStream and Jettison are you using?

**Comment by zyh5160** [comment]
my version is 1.3.8, 
When I added the second parameter, the problem was solved. 
Thank you very much !

here is the code: 

`JettisonMappedXmlDriver jsonDriver = new JettisonMappedXmlDriver(new Configuration(), false);`
