### ISSUE TITLE
performance not play well when there is 200 threads running xstream.fromXML for loop

### ISSUE THREAD

**Issue by zzjcy** [x-stream/xstream#128]
as it see blow:
private <T> T xmlToObject(String xml, Class<T> cls) {
        XStream xstream = new XStream(new DomDriver());
        xstream.processAnnotations(cls);
        return (T) xstream.fromXML(xml);
    }
this method is used to converted xml to java bean, when 200 threads running xstream.fromXML for loop,
its throughput is 177

then modify the method like this:
private <T> T xmlToObject(String xml, Class<T> cls) {
        XStream xstream = new XStream(new DomDriver());
        xstream.processAnnotations(cls);
        Class<?>[] classes = new Class[] { A.class, B.class };
        xstream.allowTypes(classes);
        return (T) xstream.fromXML(xml);
    }
use the same condition, its throughput is 360

but it is not good enough for me, can anyone give me some advice？

**Comment by joehni** [comment]
The setup of an XStream instance is an expensive act. You should always setup the XStream once. Your method above should only contain the last line. And use a proper XML parser like Xpp3 or StAX. DOM is very slow.
