### ISSUE TITLE
Ignoring write/readObject implementations for Serializable Objects

### ISSUE THREAD

**Issue by oguzdemir** [x-stream/xstream#129]
Hi, 

In my project, I am trying to record objects to disk and read them back to memory when I need. However, for Serializable classes, because of the transient fields, some of the information is missing due to the present writeObject / readObject implementations. I already set my ReflectionProvider to include transient fields, but it has no effect when the class is Serializable.  

Is there a way to simply ignore Serializable interface for classes and treat them as if they were not Serializable? (For example `java.util.EventObject` class has a transient `source` field, I cannot serialize/deserialize it )

Thanks in advance..

**Comment by joehni** [comment]
Simply register directly a ReflectionConverter for that type.

**Comment by oguzdemir** [comment]
Thanks for the reply. Actually I am developing a test tool, so I don't know which types will be involved in at the time I build my tool. Is there any other option?

**Comment by joehni** [comment]
You may register a ReflectionConverter for any Serializable then. You will just have to take care for the priority, it should be the same as for the normal SerializableConverter (see [Converters](http://x-stream.github.io/converters.html)):

``` Java
xstream.registerConverter(
  new ReflectionConverter(xstream.getMapper(), yourReflectionProvider, Serializable.class),
  XStream.PRIORITY_LOW);
```

**Comment by joehni** [comment]
You have to register with PRIORITY_LOW otherwise the SerializableConverter will take precedence. You will also have to overwrite ReflectionConverter.shouldUnmarshalTransientFields().

**Comment by oguzdemir** [comment]
I am sorry that it is taking more of your time, but the issue isn't fixed with the settings you proposed. 

I have 
```
    private ObjectRecorder() {
        SplitterJavaReflectionProvider splitterJavaReflectionProvider = new SplitterJavaReflectionProvider();
        xstream = new XStream(splitterJavaReflectionProvider);
        xstream.registerConverter(
            new SplitterReflectionConverter(xstream.getMapper(), splitterJavaReflectionProvider, Serializable.class),
            XStream.PRIORITY_VERY_HIGH);
    }
```
and
```
class SplitterReflectionConverter extends ReflectionConverter {
    
    public SplitterReflectionConverter(Mapper mapper,
        ReflectionProvider reflectionProvider, Class type) {
        super(mapper, reflectionProvider, type);
    }

    @Override
    protected boolean shouldUnmarshalTransientFields() {
        return true;
    }

    @Override
    protected void doMarshal(Object source, HierarchicalStreamWriter writer,
        MarshallingContext context) {
        System.out.println("X");
        super.doMarshal(source, writer, context);
    }
}
```

The "X" is never printed, and when I debug the code, SerializableConverter's method is executed.

**Comment by joehni** [comment]
Sorry, I forgot that an instance of a ReflectionConverter that is configured for an explicit type, will only convert that explicit type. So you will have to overwrite canConvert in your SplitterReflectionConverter and return true for all assignable types (i.e. all Serializable types).

**Comment by oguzdemir** [comment]
Oh it works now! Thank you so much again for your time!
