### ISSUE TITLE
some classes hava same @XStreamAlias, then invoke  toXML() method throws UnknownFieldException

### ISSUE THREAD

**Issue by zzjcy** [x-stream/xstream#130]
I have four classes which has the same alias like this " @XStreamAlias("MESSAGE")", 
the classes content as follows:
@XStreamAlias("MESSAGE")
public class QueryV1Request implements IRequest {
    @XStreamAlias("MHEAD")
    private V1HeadRequest head;
    @XStreamAlias("MBODY")
    private QueryV1RequestBody body;

    getter/setter method
}

@XStreamAlias("MESSAGE")
public class QueryV2Request implements IRequest {
    @XStreamAlias("MHEAD")
    private V2HeadRequest head;
    @XStreamAlias("MBODY")
    private QueryV2RequestBody body;

     getter/setter method
}

the XmlUtil class looks as follows:

public final class XmlUtil {
    private static final ThreadLocal<XStream> HOLDER = ThreadLocal.withInitial(XmlUtil::getXStream);
    private static XStream getXStream() {
        return new XStream(new XppDriver(new XmlFriendlyNameCoder("_-", "_")));
    }
    public static <T> T xmlToObject(String xml, Class<T> cls) {
        if (HOLDER.get() == null) {
            HOLDER.set(getXStream());
        }
        HOLDER.get().processAnnotations(cls);
        HOLDER.get().allowTypes(new  Class[]{cls});
        return (T) HOLDER.get().fromXML(xml);
    }
}

my question is when invoking xmlToObject() method to converting xml to java bean with the same  @XStreamAlias("MESSAGE"),  it always throws  UnknownFieldException, 

i dont know why this happened? the XStream object  only relates to the current thread, can someone help me please?

**Comment by zzjcy** [comment]
the scenario describes as belows:
1. I will receive a xml message, then convert it to QueryV1Request.
2. then use QueryV1Request to do bussiness process
3. In the end fill in the QueryV1Response object and convert it to xml, then response to client

one thread only deals with two class  like  QueryV1Request  and  QueryV1Response

**Comment by joehni** [comment]
As I already said in #128, you should setup an XStream instance once and then you can use it concurrently.

Your ThreadLocal is completely useless for your scenario. I guess you're running in some kind of Java server environment. Such an environment typically controls it threads in a thread pool. So what happens here:

0. For an incoming request V1 your server selects idle thread A from the pool
0. The ThreadLocal creates an instance of XStream for thread A
0. You configure XStream instance A for V1 types
0. You deserialize the V1 request
0. Thread A gets back into the pool
0. For an incoming request V1 your server selects idle thread A again from the pool
0. The ThreadLocal provides the existing instance of XStream for thread A already configured for V1 types
0. You configure XStream instance A nonetheless also for V2 types which use same aliases
0. You try to deserialize the V2 request
0. BOOOOOM

Got it? What you actually need are individual XStream instances, each one configured for the proper types. Something along this (I did not try to compile it, just written by heart):

``` Java
public final class XmlUtil {
  private final static ConcurrentMap<Class<?>, XStream> XSTREAMS = new ConcurrentHashMap<>();
  private XStream getXStream(Class<?> type) {
    return XSTREAMS.computeIfAbsent(type, t -> {
      XStream xstream = new XStream(new XppDriver(new XmlFriendlyNameCoder("-", "")));
      xstream.processAnnotations(t);
      xstream.allowTypes(new Class[]{t});
      return xstream;
    })
  }
  public static T xmlToObject(String xml, Class<T extends IRequest> cls) {
    return (T)XSTREAMS.get(cls).fromXml(xml);
  }
}
```
