### ISSUE TITLE
Use of autoboxing caches in xstream 1.5

### ISSUE THREAD

**Issue by dlichtenberger** [x-stream/xstream#134]
Being used to Java 1.5+ it is probably common to view boxed primitives with "small" values (e.g. Integers between -127 and +128) as harmless in terms of memory usage, as they are automatically cached by the JVM.

I recently stumbled over many duplicated instances of Integer(0), Integer(1) in a heap dump that were introduced by XStream deserialization of large object graphs.

After changing primitive converters like IntegerConverter in XStream master to use autoboxing, quite a few tests fail because Integers of the same value may now be aliased to the same object after deserialization, for example  AbstractReferenceTest.testReferencesNotUsedForImmutableValueTypes.

Would you consider changing this behaviour for xstream 1.5 (which will require Java 5 AFAICT), or is it necessary to use custom converters?

**Comment by joehni** [comment]
We will not use autoboxing, but explicit calls to Integer.valueOf(int) available since Java 1.5. Same applies for Long, Short, Character and Byte. The Java runtime will then decide which object will be reused. Thanks for spotting.
