### ISSUE TITLE
DuplicateFieldException with two elements from different namespace

### ISSUE THREAD

**Issue by sosul** [x-stream/xstream#138]
I'm sorry for referring external link [https://stackoverflow.com/questions/54760315/how-to-parse-two-elements-with-same-field-name-but-different-namespace-in-xml-us](url), having problem with editing XML and code samples here.

If there are two elements with same field name but different namespace, how should I define classes for each of them, and how should I configure StaxDriver?

**Comment by joehni** [comment]
Hi,

fist you have to realize, that XStream is made to write Java to XML and read this generated XML back, i.e. if you want to read XML of a special format, you should try setup the XStream instance so, that it can write it. Simply guessing what XStream will actually read, will be an annoying task.

Then some basic principles:
1. Defining the same alias for two different types will clobber each other
1. Defining the same alias for two elements of the same type will clobber each other
1. XStream's alias mechanism does not know anything about namespaces
1. The namespace support is based on the native parser and writer of StAX, XStream allows you only to configure those
1. There are no annotations for that configuration
1. Keep XStream away from the _xmlns_ attributes, those belong to StAX

Said that, here's a an example from the unit tests:
```java
public void testUsingDifferentNamespacesSameAliases() {
    final QNameMap qnameMap = new QNameMap();
    qnameMap.setDefaultNamespace(getDefaultNS(Handler.class));
    qnameMap.registerMapping(new QName(getDefaultNS(String.class)+1, "item"), "aStr");
    qnameMap.registerMapping(new QName(getDefaultNS(Integer.class)+2, "item"), "anInt");

    final StaxDriver driver = new WstxDriver(qnameMap);
    driver.setRepairingNamespace(false); // just for demo
    final XStream xstream = new XStream(driver);
    // setup security stuff
    xstream.alias("handler", X.class);
    xstream.aliasField("protocol", X.class, "innerObj");

    final X x = new X();
    x.aStr = "foo";
    x.anInt = 42;
    x.innerObj = new Y();
    x.innerObj.yField = "YField";

    final String expected = XML_HEADER
        + "<handler xmlns=\"java://com.thoughtworks.acceptance.someobjects\">"
        + /**/ "<item xmlns=\"java://java.lang1\">foo</item>"
        + /**/ "<item xmlns=\"java://java.lang2\">42</item>"
        + /**/ "<protocol>"
        + /**//**/ "<yField>YField</yField>"
        + /**/ "</protocol>"
        + "</handler>";

    assertBothWays(x, expected);
}

```

You see, the alias mechanism used here for the local name of the namespace is implemented using the _QNameMap._ XStream itself still refers the two elements internally as _aStr_ and _anInt._

_X_ is a test type, you see the field types in the test code by the assigned types. The _getDefaultNS_ method is just for the unit test, it creates namespaces like you can see in the expected XML. The _assertBothWays_ method will first convert the given object to XML, compare that XML to the expected one, unmarshal the XML back to an object and compare that one with the original.

Hope this helps,
Jörg
