### ISSUE TITLE
Hello, I have some questions for you to answer

### ISSUE THREAD

**Issue by JueShan** [x-stream/xstream#143]
Hello, I just came into contact with xstream recently，xstream is so great, But in the process of using,I found xstream processing the xml statement is not so firendly , I turned the javabeans into XML files, But I found that I couldn't load the XML statement file successfully , Take an  example ，The xml header "<?xml version="1.0" encoding="GBK"?>" , How can I put the xml statement in a Java bean and convert it into XML together?  
At present, I override the xstream toXML(Object obj, OutputStream out) method, add an XML template declaration information by  override the  toXML() 
Is there a better way? Please reply to me Thank you .

**Comment by joehni** [comment]
XStream turns Java objects into XML (or JSON, or ...) and back. The object graph is represented only by the XML elements, the XML header is part of the _format_ and has therefore no representation in the object graph.

The FAQ explains, why XStream does not write the [XML header](http://x-stream.github.io/faq.html#XML_write_XML_declaration) and what it means for the [encoding](http://x-stream.github.io/faq.html#XML_write_UTF8).

**Comment by SuperChrisliu** [comment]
@joehni 

> XStream turns Java objects into XML (or JSON, or ...) and back. The object graph is represented only by the XML elements, the XML header is part of the _format_ and has therefore no representation in the object graph.
> 
> The FAQ explains, why XStream does not write the [XML header](http://x-stream.github.io/faq.html#XML_write_XML_declaration) and what it means for the [encoding](http://x-stream.github.io/faq.html#XML_write_UTF8).


[XML_write_UTF8](http://x-stream.github.io/faq.html#XML_write_UTF8)
someone have a example?

**Comment by joehni** [comment]
What kind of example? How to create an [OutputStreamWriter](https://docs.oracle.com/javase/8/docs/api/java/io/OutputStreamWriter.html) with a specific encoding and providing that as output channel for [XStream](https://x-stream.github.io/javadoc/com/thoughtworks/xstream/XStream.html#toXML-java.lang.Object-java.io.Writer-)?

**Comment by SuperChrisliu** [comment]
> What kind of example? How to create an [OutputStreamWriter](https://docs.oracle.com/javase/8/docs/api/java/io/OutputStreamWriter.html) with a specific encoding and providing that as output channel for [XStream](https://x-stream.github.io/javadoc/com/thoughtworks/xstream/XStream.html#toXML-java.lang.Object-java.io.Writer-)?


yes, now i figure it out: 
```
        ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
        Writer out = new BufferedWriter(new OutputStreamWriter(byteArrayOutputStream, StandardCharsets.UTF_8));
        xstream.toXML(record, out);
        out.flush();
        System.out.println(byteArrayOutputStream.toString("utf-8"));
```

thank you
