### ISSUE TITLE
Can't update to latest version 1.4.11 because of typo in pom.xml

### ISSUE THREAD

**Issue by jowerner** [x-stream/xstream#144]
I wanted to update Xstream to the latest version 1.4.11-java7, but I'm struggling getting my project to build. The project still uses Ant together with the Maven Ant Tasks for the build. Ant complains about a typo in the parent pom of Xstream and refuses to download Xstream from the Maven repo:

```
[artifact:dependencies] An error has occurred while processing the Maven artifact tasks.
[artifact:dependencies]  Diagnosis:
[artifact:dependencies]
[artifact:dependencies] Unable to resolve artifact: Unable to get dependency information: Unable to read the metadata file for artifact 'com.thoughtworks.xstream:xstream:jar': Invalid JDK version in profile 'jdk9-ge': Unbounded range: [9, for project com.thoughtworks.xstream:xstream-parent
[artifact:dependencies]   com.thoughtworks.xstream:xstream:jar:1.4.11-java7
```
I can see that in the meantime this typo has already been fixed with commit a024fdf. Would you mind providing a new minor release with this fix or alternatively push a fixed pom.xml to the Maven repo? Thanks!

**Comment by joehni** [comment]
As you've found out, the problem is already fixed. However, I plan to release 1.4.12 soon ...

**Comment by thhart** [comment]
This looks broken very long now, I can not receive 1.4.11.1 from Maven repos. Any chance to fix soon?
