### ISSUE TITLE
Please use SPDX license identifier

### ISSUE THREAD

**Issue by vlsi** [x-stream/xstream#151]
AFAIKU the license is BSD-3-Clause (see https://spdx.org/licenses/BSD-3-Clause.html ).
Could you please use that identifier so it is machine-readable?

Suggested changes are:

`<name>BSD-3-Clause</name>` here: https://github.com/x-stream/xstream/blob/9069fcb5abc32af8b6088a26fde2b5b7e8216101/pom.xml#L226

PS. It would be nice to use SPDX license id in `Bundle-License` manifest attribute as well.

**Comment by vlsi** [comment]
Thank you for the quick fix

**Comment by vlsi** [comment]
PS you might want to use SPDX identifier in `Bundle-License` manifest attribute as well.
That would enable analysis of the jar file without downloading `pom.xml` for it (which is not available when you examine a standalone jar file).

See https://osgi.org/specification/osgi.core/7.0.0/framework.module.html#framework.module-bundle-license

**Comment by joehni** [comment]
This has been already done with the closing commit.

**Comment by vlsi** [comment]
Indeed. It looks like I missed that.
