### ISSUE TITLE
OSGi import of package com.ibm.xml.xlxp.api.stax should be resolution:=optional

### ISSUE THREAD

**Issue by wilx** [x-stream/xstream#152]
The XStream core package 1.4.11.1 does not resolve in OSGi environment with Oracle Java. This seems to be because its OSGi manifest is requiring import of package `com.ibm.xml.xlxp.api.stax`. This appears to be IBM Java specific package, judging from this code in `com.thoughtworks.xstream.core.JVM#getStaxInputFactory`:

```java
    public static Class<? extends XMLInputFactory> getStaxInputFactory() throws ClassNotFoundException {
        if (isIBM()) {
            return (Class<? extends XMLInputFactory>)Class.forName("com.ibm.xml.xlxp.api.stax.XMLInputFactoryImpl");
        } else {
            return (Class<? extends XMLInputFactory>)Class.forName("com.sun.xml.internal.stream.XMLInputFactoryImpl");
        }
    }
```

The import should be marked with `resolution:=optional`:

```diff
diff --git a/xstream/pom.xml b/xstream/pom.xml
index e1b0986b..353346a4 100644
--- a/xstream/pom.xml
+++ b/xstream/pom.xml
@@ -394,7 +394,7 @@

   <properties>
     <bundle.export.package>!com.thoughtworks.xstream.core.util,com.thoughtworks.xstream.*;-noimport:=true</bundle.export.package>
-    <bundle.import.package>org.xmlpull.mxp1;resolution:=optional,org.xmlpull.v1;resolution:=optional,*</bundle.import.package>
+    <bundle.import.package>org.xmlpull.mxp1;resolution:=optional,org.xmlpull.v1;resolution:=optional,com.ibm.xml.xlxp.api.stax;resolution:=optional,*</bundle.import.package>
   </properties>

 </project>
```

**Comment by wilx** [comment]
Now that I think of it, the `com.sun.xml.internal.stream` package should be also imported with `resolution:=optional` so that the OSGi bundle works on AIX with IBM Java.

**Comment by joehni** [comment]
These are packages of the specific Java runtimes. Why should those be imported?

**Comment by wilx** [comment]
@joehni I guess that depends OSGi runtime and its setup. Ideally, AFAIK, everything you use should be imported. In any case, the [1.4.11.1 version](https://repo1.maven.org/maven2/com/thoughtworks/xstream/xstream/1.4.11.1/xstream-1.4.11.1.jar) downloadable from central repository contains OSGi manifest that contains this (I have highlighted the important parts:

> Import-Package: org.xmlpull.mxp1;resolution:=optional,org.xmlpull.v1;r
>  esolution:=optional,com.bea.xml.stream;resolution:=optional,com.ctc.w
>  stx.stax;resolution:=optional,**com.ibm.xml.xlxp.api.stax,com.sun.xml.i
>  nternal.stream**,javax.activation,javax.security.auth,javax.swing,javax

As you can see, both internals of IBM Java and Oracle Java are imported without any qualifiers, so they are hard requirements and the OSGi bundle won't resolve in either Java.

**Comment by wilx** [comment]
And now that I look closer, I am not sure if `sun.misc` import is compatible with IBM Java either.

**Comment by joehni** [comment]
sun.misc is available in any Java runtime ... ;-)

However, I've configured the bundle plugin now to import all classes as optional.
