### ISSUE TITLE
Problems with fromXML

### ISSUE THREAD

**Issue by Zyuxing** [x-stream/xstream#155]
<person>
  <firstname>Joe</firstname>
  <lastname>Wal<i>f</i>bnes</lastname>
</person>
When I use xstream fromXML (), have a special character in the XML node, xstream will lose this part of the data, the results into a Person [firstname = Joe, lastname = a Wal], this part of the <i>f</i> bnes data will be lost, could you tell me how to deal with him, I this is just a example, actually XML is very big, and is the third party to provide, so can't to generate XML processing, can only resolve others

**Comment by Zyuxing** [comment]
<person>
  <firstname>Joe</firstname>
  <lastname>Wal<i>f</i>bnes</lastname>
</person>
Joe Walfbnes When I use xstream fromXML (), have a special character in the XML node, xstream will lose this part of the data, the results into a Person [firstname = Joe, lastname = a Wal], this part of the f bnes data will be lost, could you tell me how to deal with him, I this is just a example, actually XML is very big, and is the third party to provide, so can't to generate XML processing, can only resolve others

**Comment by Zyuxing** [comment]
`<person>
  <firstname>Joe</firstname>
  <lastname>Wal<i>f</i>bnes</lastname>
</person>`
When I use xstream fromXML (), have a special character in the XML node, xstream will lose this part of the data, the results into a Person [firstname = Joe, lastname = a Wal], this part of the <i>f</i> bnes data will be lost, could you tell me how to deal with him, I this is just a example, actually XML is very big, and is the third party to provide, so can't to generate XML processing, can only resolve others

**Comment by Zyuxing** [comment]
`<person>
  <firstname>Joe</firstname>
  <lastname>Wal<i>f</i>bnes</lastname>
</person>`
When I use xstream fromXML (), have a special character in the XML node, xstream will lose this part of the data, the results into a Person [firstname = Joe, lastname = a Wal], this part of the <i>f</i> bnes data will be lost, could you tell me how to deal with him, I this is just a example, actually XML is very big, and is the third party to provide, so can't to generate XML processing, can only resolve others

**Comment by joehni** [comment]
Sorry, but XStream does not support mixed XML content in any way. You cannot use it to read such kind of XML.
