### ISSUE TITLE
XStream serialization bug

### ISSUE THREAD

**Issue by incube8r** [x-stream/xstream#158]
I'm not sure if this is an XStream bug but when you have a resource like this
```
    List<User> getUsers() {}
```
And this resource returns a single element List then the resulting JSON string is like this
```
    { "users" : { "id" : 1 } } 
```
Instead of 

```
    { "users" : [{ "id" : 1 }] } 
```
The problem here is the result was not JSON array as expected.

Is there a workaround for this bug?

**Comment by joehni** [comment]
Use Jettison 1.2.

**Comment by incube8r** [comment]
@joehni my app already uses 1.3.5 do you mean a downgrade is required?

```
[INFO] +- org.restlet.jee:org.restlet.ext.xstream:jar:2.3.12:compile
[INFO] |  \- org.codehaus.jettison:jettison:jar:1.3.5:compile
[INFO] |     \- stax:stax-api:jar:1.0.1:compile

```

**Comment by joehni** [comment]
See #72 and version information at [download](http://x-stream.github.io/download.html) page. I've reported this problem for Jettison 1.3.x already 7 years ago as JETTISON-111 at Codehaus' JIRA. Nothing happened though.
