### ISSUE TITLE
@XStreamConverter and registerLocalConverter do not work on attribute fields

### ISSUE THREAD

**Issue by jimmyli97** [x-stream/xstream#16]
I've so far been unable to come up with anything relating to this issue except for the following mailing list issue regarding this: http://markmail.org/thread/qkgmgewmplmav4kc

The following results in the local converter being ignored:
```
public class Formula {
@XStreamAlias("score")
@XStreamAsAttribute
@XStreamConverter(ScoreConverter.class)
private String score;
}
```

I've also tried ```XStream.registerLocalConverter(Formula.class, "score", new ScoreConverter())```, but it still does not work.

Only when I remove the @XStreamAsAttribute annotation does the local converter work as expected.

According to the mailing list, the only workaround is to write a custom converter for the entire class. This class has a lot of fields, and I'd much rather allow the default converter to take over for most of the fields and only handle the score field manually.

Is there really no alternative but to write a custom converter for the entire class? 

As a side note, what I'm trying to do is to make the attribute optional - as in, the score attribute will not show up if the score is empty. Is this the right way to go about doing so?

**Comment by joehni** [comment]
I suppose, your converter is not a SingleValueConverter as required for attributes? See [tutorial](x-stream.github.io/converter-tutorial.html#SingleValueConverter). And there is no need to set "score" as alias for "score".

The attribute will only vanish, if score is null.

**Comment by jimmyli97** [comment]
Thank you very much! I missed that line when i was going through the
tutorials/
