### ISSUE TITLE
OSGi requirement for Java 8

### ISSUE THREAD

**Issue by grgrzybek** [x-stream/xstream#175]
Despite XStream ability to run on different JDKs, there's one `META-INF/MANIFEST.MF` header that prevents it.
With `git bisect` I found that 42ef0ae4 (related to #75) added this header:
```
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
```
This is added after upgrade of maven-bundle-plugin from 2.3.7 to 2.5.4 (which inflicts bndlib update from 1.50.0 to 2.4.1).
Without any reference to any JIRA/GH issue, https://github.com/bndtools/bnd/commit/b4a16c2496ec32ce83991d0cea41595a87c65fb7 commit brought implicit addition of `Require-Capability: osgi.ee` header.

I think it'd be good to add:
```
diff --git a/pom.xml b/pom.xml
index 861977c5..5165b8a0 100644
--- a/pom.xml
+++ b/pom.xml
@@ -837,6 +837,7 @@
             <manifestLocation>${project.build.directory}/OSGi</manifestLocation>
             <instructions>
               <_nouses>true</_nouses>
+              <_noee>true</_noee>
               <Bundle-SymbolicName>${project.artifactId}</Bundle-SymbolicName>
               <Specification-Version>${project.info.majorVersion}.${project.info.minorVersion}</Specification-Version><!-- FELIX-3392 -->
             </instructions>
```
(diff against 42ef0ae4)

**Comment by joehni** [comment]
Already fixed.

**Comment by grgrzybek** [comment]
Sorry for confusion. I checked first against 1.4.10 and then just created a PR with this diff for master branch. Please excuse me ;)

**Comment by joehni** [comment]
No problem. Thanks for heads-up.
