### ISSUE TITLE
XStream - Why readObject or readResolve are not called for Parent class?

### ISSUE THREAD

**Issue by yccheok** [x-stream/xstream#178]
I have the following class

Child.java
----------

    public class Child extends Parent {
        private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
            in.defaultReadObject();
            System.out.println("Child readObject");
        }
        
        private Object readResolve() {
            System.out.println("Child readResolve");
            return this;
        }
    }

Parent.java
-----------

    public class Parent {
        private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
            in.defaultReadObject();
            System.out.println("Parent readObject");
        }
        
        private Object readResolve() {
            System.out.println("Parent readResolve");
            return this;
        }    
    }

We are using latest XStream 1.4.11.1

We expect when we de-serialize `Child` object from disk, either `readResolve` or `readObject` will be triggered, for both `Child` and `Parent` class.

Main.java
---------

    public class Main {
        /**
         * Performs close operation on Closeable stream, without the need of
         * writing cumbersome try...catch block.
         *
         * @param closeable The closeable stream.
         */
        public static void close(Closeable closeable) {
            if (null != closeable) {
                try {
                    closeable.close();
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            }
        }
        
        @SuppressWarnings("unchecked")
        public static <A> A fromXML(Class c, Reader reader) {
            // Don't ever try to use DomDriver. They are VERY slow.
            XStream xStream = new XStream();
    
            try {
                Object object = xStream.fromXML(reader);
                if (c.isInstance(object)) {
                    return (A)object;
                }
            }
            catch (Exception exp) {
                exp.printStackTrace();
            }
            finally {
                /* The caller shall close reader explicitly. */
            }
    
            return null;
        }
    
        @SuppressWarnings("unchecked")
        public static <A> A fromXML(Class<A> c, File file) {
            // Don't ever try to use DomDriver. They are VERY slow.
            XStream xStream = new XStream();
            InputStream inputStream = null;
            Reader reader = null;
    
            try {
                inputStream = new java.io.FileInputStream(file);
                reader = new InputStreamReader(inputStream, Charset.forName("UTF-8"));
                Object object = xStream.fromXML(reader);
    
                if (c.isInstance(object)) {
                    return (A)object;
                }
            }
            catch (Exception exp) {
                exp.printStackTrace();
            } catch (java.lang.Error err) {
                err.printStackTrace();
            } finally {
                close(reader);
                close(inputStream);
            }
    
            return null;
        }
    
        @SuppressWarnings("unchecked")
        public static <A> A fromXML(Class<A> c, String filePath) {
            return fromXML(c, new File(filePath));
        }
    
        public static boolean toXML(Object object, File file) {
            XStream xStream = new XStream();
            OutputStream outputStream = null;
            Writer writer = null;
    
            try {
                outputStream = new FileOutputStream(file);
                writer = new OutputStreamWriter(outputStream, Charset.forName("UTF-8"));
                xStream.toXML(object, writer);
            }
            catch (Exception exp) {
                exp.printStackTrace();
                return false;
            }
            finally {
                close(writer);
                close(outputStream);
            }
    
            return true;
        }
    
        public static boolean toXML(Object object, String filePath) {
            return toXML(object, new File(filePath));
        }
    
        /**
         * @param args the command line arguments
         */
        public static void main(String[] args) {
            // TODO code application logic here
            Child child = new Child();
            
            System.out.println("=== toXML ===");
            toXML(child, "c:\\yocto\\a.txt");
            
            System.out.println("=== fromXML ===");
            fromXML(Child.class, "c:\\yocto\\a.txt");
        }
        
    }

----------

The printed output is

    === toXML ===
    === fromXML ===
    Child readResolve

----------

May I know how I can make `readObject`, or `readResolve` being triggered for Parent class? 

According to XStream documentation https://x-stream.github.io/faq.html , at least `readObject` should be triggered for Parent class.

**Comment by joehni** [comment]
Your classes do not implement Serializable. While readResolve and writeReplace is also supported for non-serializable types, this is not true for readObject and writeObject, because these methods rely on Java Serialization for the streams.

**Comment by yccheok** [comment]
Thanks for swift response. 

Previously, in `1.4.2`, we didn't implement `Serializable`. Yet, `readResolve` still being called in Parent class.

We use `1.4.11.1` as we need to support Java 11. Seem like previous behavior no longer valid.

I manage to solve this issue by letting Parent implements Serializable.

May I know, does Child class need to implements Serializable as well, although I find it works well even without implements Serializable?

Also, may I suggest documentation for https://x-stream.github.io/faq.html to be updated? As under section "How do I initialize a transient field at deserialization?", the given code example is without "implements Serializable". This might puzzle developers on why `readObject` is not being called.

Thank you for supporting, keeping XStream alive.

**Comment by joehni** [comment]
Thanks. Docs are improved for the next version.
