### ISSUE TITLE
Support AdoptOpenJDK as a vendor

### ISSUE THREAD

**Issue by andreild** [x-stream/xstream#183]
Hello,

I'd like to request that com.thoughtworks.xstream.core.JVM#bestReflectionProvider be updated such that either
- it recognises "AdoptOpenJDK" as a vendor for which it can use the `com.thoughtworks.xstream.converters.reflection.Sun14ReflectionProvider` reflection provider, OR
- it stops checking the vendor entirely

I'm requesting this as I'm seeing different runtime behaviour with a "non-supported" JVM, despite the fact that this JVM appears to provide all needed features (as far as I could determine, only `sun.misc.Unsafe` is needed).

Thank you. Please let me know what you think of this idea, and whether you'd accept a PR with a change as described above.

**Comment by joehni** [comment]
Sorry, I don't know what you mean. XStream 1.4.11 does not check a vendor string to decide whether it can use the Sun14ReflectionProvider or not. Which version of XStream are you using?

**Comment by andreild** [comment]
Hello Jörg,

I was using 1.4.4. The behaviour I mentioned was in fact removed in 1.4.5, commit 8b733011502c268a534e57bb72e14717758b50d5. Since opening this ticket, I've updated to 1.4.11.1, which seems to be working just fine.

I'll close this ticket, I hope that's ok. Thank you!

**Comment by joehni** [comment]
You're welcome. I knew, it did check vendors at some time, but it took myself some time to remember the change using runtime behaviour only 7 years ago ;-)
