### ISSUE TITLE
error when parsing xml with attribute literal 'class' 

### ISSUE THREAD

**Issue by biubiu** [x-stream/xstream#185]
Hi there,
I'm trying to unmarshall some xmls and found that when parsing xml with attribute literal 'class', a CannotResolveClassException will be thrown, such error won't occur to attributes with other names. See the following test case:

`
    @Test
    public void bugs() {
        XStream xStream = new XStream();
        xStream.processAnnotations(BB.class);
        //will parse correctly when changing 'class' to something else like 'clazz'
        final String xml = ""//
                + "<bb class=\"counter\">"
                + "</bb>";
        xStream.processAnnotations(BB.class);
        final BB bb = (BB) xStream.fromXML(xml);
        System.out.println(bb);
    }

    @XStreamAlias("bb")
    public static class BB {

        @XStreamAsAttribute
        @XStreamAlias("class")
        //change alias to clazz and related attribute in xml, the test would pass  
        public String clazz;

        @Override
        public String toString() {
            return MoreObjects.toStringHelper(this)
                    .add("clazz", clazz)
                    .toString();
        }
    }
`

it would parse correctly if changing the attribute to 'clazz' or anything other than 'class'

**Comment by zeshuai007** [comment]
Hi! biubiu
Your test case is incorrect and misleading.
From the phenomenon point of view, this is indeed a problem after serialization, and then deserialization fails, provided that xstream supports the java keyword.

**Comment by joehni** [comment]
Hi buibui,

XStream uses own attributes for its management, they are called system attributes. '_class_' is one of them. However, you can configure XStream (see [FAQ](http://x-stream.github.io/faq.html#Serialization_system_attributes)) to use different ones, so that the unmarshalling of your XML is not affected. However, for this configuration exist no annotations, you have to call the appropriate methods on the XStream instance.

Cheers,
Jörg

**Comment by zeshuai007** [comment]
Hi Jörg,
In Xstream, I don't see the annotations that the system attributes of xstream are not recommended. Is this private and not public?
I verified the system properties (non-reserved keywords) of other xstreams and did not have the problem. So, does this system attribute "class" need to be commented or documented?
Please forgive my curiosity.
Cheers!

**Comment by zeshuai007** [comment]
Hi @biubiu ,
I verified resetting the system attributes and adding the code:
```
xStream.aliasAttribute("class","clazz");
xStream.aliasSystemAttribute("youSet","class");
```
You can re-convert the xml to a BB.class object.
Also, I verified the system attributes (non-reserved keywords) of other Xstreams and did not have the problem.

Cheers!

**Comment by biubiu** [comment]
> Hi @biubiu ,
> I verified resetting the system attributes and adding the code:
> 
> ```
> xStream.aliasAttribute("class","clazz");
> xStream.aliasSystemAttribute("youSet","class");
> ```
> 
> You can re-convert the xml to a BB.class object.
> Also, I verified the system attributes (non-reserved keywords) of other Xstreams and did not have the problem.
> 
> Cheers!

Thanks!
