### ISSUE TITLE
External target class causes deserialization failure

### ISSUE THREAD

**Issue by Alanscut** [x-stream/xstream#188]
when I Deserialize a xml string, the target class  I assigned is generated from an external class file, it will report an error. how can I solve this issue?
```java
URL url = new URL("file:///temp/class/VO.jar");
URLClassLoader classLoader = new URLClassLoader(new URL[]{url});
clazz = classLoader.loadClass("VO");
classLoader.close();

return xStream.fromXML(xml, clazz); // report an error
```
error stack:
```
Exception in thread "main" com.thoughtworks.xstream.mapper.CannotResolveClassException: Person
	at com.thoughtworks.xstream.mapper.DefaultMapper.realClass(DefaultMapper.java:81)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:125)
	at com.thoughtworks.xstream.mapper.DynamicProxyMapper.realClass(DynamicProxyMapper.java:55)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:125)
...
```

**Comment by joehni** [comment]
A classloader has to be provided with XStream's constructor. And you should believe the Javadoc for xstream.fromXML with two arguments and never use it until you really know what you do. Currently XStream will try write into the provided class object.

**Comment by Alanscut** [comment]
@joehni Thanks your explalation, my intend is to deserialize an xml string as a specified class, but the class can only be determined at runtime, so I have to receive the deserialized object with `java.lang.Object`.
what I want to do is just like the below example, can you give me some advice?

I tested it successfully with Gson:
```java
public static void main(String[] args) throws UnsupportedEncodingException {
    Gson gson = new Gson();
    Class clazz = getClassByClassLoader();
    Object object = gson.fromJson(json, clazz);  // deserialize the json string as type `clazz`
    System.out.println(object.getClass().getTypeName());  // print Person
}

private static Class<?> getClassByClassLoader() {
    Class<?> clazz = null;
    try {
        URL url = new URL("file:///temp/class/Person.jar");
        URLClassLoader classLoader = new URLClassLoader(new URL[]{url});
        clazz = classLoader.loadClass("Person");
        classLoader.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
    return clazz;
}
```

**Comment by Alanscut** [comment]
I got it. specifying the class in `xStream.alias` and removing the second parameter in `xStream.fromXML` will ok.
```
XStream xStream = new XStream();
Class clazz = getClassByClassLoader();
xStream.alias("person", clazz);
Object object = xStream.fromXML(xml);
```

**Comment by Alanscut** [comment]
> I got it. specifying the class in `xStream.alias` and removing the second parameter in `xStream.fromXML` will ok.
> 
> ```
> XStream xStream = new XStream();
> Class clazz = getClassByClassLoader();
> xStream.alias("person", clazz);
> Object object = xStream.fromXML(xml);
> ```

still not working.

**Comment by Alanscut** [comment]
It seems that when set ClassLoader it will ok. Should I do this?
```
XStream xStream = new XStream();
Class clazz = getClassByClassLoader();
xStream.setClassLoader(clazz.getClassLoader());  // when add this, it is ok.
xStream.alias("person", clazz);
Object object = xStream.fromXML(xml);
```

**Comment by joehni** [comment]
I did not mention an alias at any time. An alias would be necessary if the XML contains an XML tag named "person" e.g. as root.

As said, you have to provide the classloader. You did it now with XStream's setClassLoader method, which is fine, if its the first method called after instantiating the XStream. I proposed to provide it with the constructor. Nevertheless, you found a correct solution.
