### ISSUE TITLE
Xstream vs. serialPersistentFields

### ISSUE THREAD

**Issue by apreg** [x-stream/xstream#19]
So [xstream](http://grepcode.com/file/repo1.maven.org/maven2/com.thoughtworks.xstream/xstream/1.4.8/com/thoughtworks/xstream/converters/reflection/SerializableConverter.java?av=f#295) (v1.4.8) with this line
```
private Object More ...readField(ObjectStreamField field, Class type, Object instance) {
        try {
           Field javaField = type.getDeclaredField(field.getName());
```
tries to reach the field named "list" (field.getName() returns "list")
```
private static final ObjectStreamField[] serialPersistentFields = {
             new ObjectStreamField("list", VirtualFilePermission[].class)
     };
```
declared in [org.jboss.vfs.VirtualFilePermissionCollection](http://grepcode.com/file/repository.jboss.org/nexus/content/repositories/releases/org.jboss/jboss-vfs/3.2.9.Final/org/jboss/vfs/VirtualFilePermissionCollection.java#34) but runs into NoSuchFieldException. Why is that?

**Comment by apreg** [comment]
I got the reason:
"An ObjectStreamField describes a field that is stored in the serialized stream. While the default mechanism will create an ObjectStreamField for each real instance field of a class, the possibility to override it via a static final ObjectStreamField[] serialPersistentFields field exists exactly for the purpose to declare a list of stream fields which do not match the actual instance fields.

Such fields can’t be processed by the default algorithm of just reading and writing field values via Reflection. Instead, the dedicated writeObject and readObject methods are required which will read and write the stream fields and process their values.

The problem here is that the class VirtualFilePermissionCollection has such a mismatching field declaration, as the stream field is named list and the actual instance field is named permissions, and an appropriate readObject method (despite its unnecessary use of Reflection to access its field) but lacks a matching writeObject method. Since a dedicated writeObject method is missing, the default algorithm is used and fails because, as said, the fields don’t match."
[StackOverflow](http://stackoverflow.com/questions/31270387/reaching-static-field-declared-in-serialpersistentfields)
Now I'm interested in possible solutions.

**Comment by joehni** [comment]
Can you try to serialize and deserialize such an object with plain Java serialization? Just being curious...

**Comment by apreg** [comment]
I cannot, sorry. I don't know how I got there. I mean why it tries to serialize that class which belongs to jboss.

**Comment by joehni** [comment]
1/ I doubt that you can serialize and deserialize that class with Java serialization. The implementation violates the specification and therefore XStream's SerializationConverter fail. All you can do is to write a [custom converter](http://x-stream.github.io/converter_tutorial.html) for this type and register the converter in the XStream instance.

2/ If you wonder, why such an instance is marshalled at all, you have to look at the thrown exception. It should contain the XPath to the element where the error happened. That path should give you a hint where the part in the XML begins that should not have been contained.

**Comment by apreg** [comment]
Thanks. I'll try to do what you suggested.

**Comment by apreg** [comment]
"It should contain the XPath to the element where the error happened. That path should give you a hint where the part in the XML begins that should not have been contained."
I try to convert object to xml so I guess what you mentioned does not help in this case.

**Comment by joehni** [comment]
Sorry, you're right. It keeps the path only at deserialization.
