### ISSUE TITLE
To support the encoding and decoding of RFC4648_URLSAFE

### ISSUE THREAD

**Issue by zeshuai007** [x-stream/xstream#192]
Starting in Java 8, the Base64 codec is finally defined as a standard API, and also supports RFC4648_URLSAFE codec (using the base64 encoding scheme of URL and filename types)
However, XStream has now been upgraded to Java8. Should it support RFC4648_URLSAFE in Base64JavaUtilCodec, or should it be deprecated?
Any comments?

**Comment by joehni** [comment]
Actually it is already supported. Just use a different constructor for Base64JavaUtilCodec. However, you're right. With the Java 8 requirement, we can drop the other Base64 codecs, the one of the Java runtime was the fastest anyway. Therefore I've Renamed Base64JavaUtilCodec to Base64COde and moved it into the parent package - which will make the class part of the official API.
