### ISSUE TITLE
Is the XML header encoding UTF-8 uppercase or lowercase?

### ISSUE THREAD

**Issue by zeshuai007** [x-stream/xstream#195]
Hi ! 

When processing XML headers, if the stream does not contain XML headers or no attributes are set in the header, **[XmlHeaderAwareReader](https://github.com/x-stream/xstream/blob/08ebd1271699891e8922bdb011e7ba20013f64cb/xstream/src/java/com/thoughtworks/xstream/core/util/XmlHeaderAwareReader.java#L69)** will set version 1.0 and encoding UTF-8 by default, which meets the specification:
February 3, 2005, according to the StAX 1.0 specification, the version should be "1.0" and encoded as "utf-8" (lowercase), but we all know that this is wrong and we should ignore it, so change to (uppercase) What do you think?

**Comment by joehni** [comment]
The XML spec says uppercase ;-)
