### ISSUE TITLE
Can non-enhanced mode be used to avoid illegal reflections?

### ISSUE THREAD

**Issue by zeshuai007** [x-stream/xstream#197]
Hi,

Now XStream is in enhanced working mode by default, and almost all converters will be initialized. This will undoubtedly do a lot of initialization work, but converters using Fields in java9 or higher environment will have warnings (illegal reflection),
This troubles most people, maybe their work does not depend on the enhanced work mode,
Only need to initialize IntConverter, DateConverter and other basic converters
```
protected void setupConverters() {
                registerConverter(new NullConverter(), PRIORITY_VERY_HIGH);
                registerConverter(new IntConverter(), PRIORITY_NORMAL);
                registerConverter(new FloatConverter(), PRIORITY_NORMAL);
                registerConverter(new DoubleConverter(), PRIORITY_NORMAL);
                registerConverter(new LongConverter(), PRIORITY_NORMAL);
                registerConverter(new ShortConverter(), PRIORITY_NORMAL);
                registerConverter(new BooleanConverter(), PRIORITY_NORMAL);
                registerConverter(new ByteConverter(), PRIORITY_NORMAL);
                registerConverter(new StringConverter(), PRIORITY_NORMAL);
                registerConverter(new DateConverter(), PRIORITY_NORMAL);
                registerConverter(new CollectionConverter(getMapper()), PRIORITY_NORMAL);
                registerConverter(new ReflectionConverter(getMapper(), getReflectionProvider()), PRIORITY_VERY_LOW);
            }
```
So, is it possible to make XStream's default working mode any mode that is not enhanced.

Cheers, best regards
Ze Zeng

**Comment by joehni** [comment]
No, because the illegal access depends on the fact whether a module has been opened for XStream or not. So it depends on the individual class.
