### ISSUE TITLE
com.thoughtworks.xstream.mapper.CannotResolveClassException

### ISSUE THREAD

**Issue by dudiao** [x-stream/xstream#198]
I want to parse a 5.2G xml file, the following is a part of it
```xml
<?xml version="1.0" encoding="utf-8"?>
<Data>

    <Student>
        <Name>zhangshan</Name>
    </Student>

    <Person id="201036" action="insert" date="2019">
        <Gender>Male</Gender>
        <Name>wangwu</Name>
    </Person>

    <Teacher>
        <Name>lisi</Name>
    </Teacher>

</Data>
```
I just want to parse `Person`, so the entity is
```java
@Data
@XStreamAlias("Data")
public class MyData {

    @XStreamAlias("Person")
    private Person person;
}

@Data
@XStreamAlias("Person")
public class Person {

    @XStreamAsAttribute
    private String id;

    @XStreamAsAttribute
    private String action;

    @XStreamAsAttribute
    private String date;

    @XStreamAlias("Gender")
    private String gender;
}
```

The actual code is as follows
```java
        XStream xStream = new XStream();
        XStream.setupDefaultSecurity(xStream);
        xStream.addPermission(AnyTypePermission.ANY);
        xStream.processAnnotations(MyData.class);
        xStream.ignoreUnknownElements();

        String path = "E:\\test.xml";
        ObjectInputStream objectInputStream = xStream.createObjectInputStream(new FileInputStream(path));
        try {
            while (true) {

                Object o = objectInputStream.readObject();
                log.info("==> {}", o.toString());

            }
        } catch (IOException | ClassNotFoundException e) {
            if (e instanceof EOFException) {
                log.info("==> 文件结束");
            } else {
                log.error("==>", e);
            }
        } finally {
            objectInputStream.close();
        }
```

but there is an error
```
com.thoughtworks.xstream.mapper.CannotResolveClassException: Student
```
the xstream version is `1.4.11.1`, thanks

**Comment by zeshuai007** [comment]
I believe you only need to check the file test.xml, you are very smart, and you will be able to find the cause of the problem.
Process the annotations of the student type and configure the XStream, you add this to give it a try
···
xStream.processAnnotations(new Class[] {MyData.class, Person.class, Teacher.class, Student.class});
xStream.allowTypesByWildcard(new String[] {MyData.class.getPackage().getName() + ".**" });
···
I believe it will never report an error again.
Cheers

**Comment by dudiao** [comment]
@zeshuai007 thank you for your help

I only want to parse the entity I care about. `User` and `Teacher` are not my concerns. In fact, my xml has many such unrelated attributes. I don’t want to write entity one by one, and when the xml changes, I still need add entity.

Is there something wrong with my configuration?

---
我只想解析关心的实体类，user和teacher不是我关心的，事实上我的xml还有很多这种无关的属性，我不想一个一个的去写实体类，而且当xml变化时，我还需要增加实体类。

是我的配置有问题吗？

**Comment by joehni** [comment]
Hi,

an _ObjectInputStream_ is part of the Java serialization framework. In your case XStream utilizes it to omit the surrounding container (your _Data_ element, i.e. your _MyData_ type is here completely superfluous) and to provide each child as an element of the _readObject_ call. However, this functionality does not support ignoring unknown elements.

But why don't you simply call _fromXML_ and actually utilize your _MyData_ type:

```java
MyData data = (MyData)xStream.fromXML(new File(path));
```
The ignored stuff won't consume any memory.

BTW: You realize, that your configuration of XStream's security framework makes this instance vulnerable for any known security whole?

**Comment by zeshuai007** [comment]
Hi @dudiao 

I probably understand what you mean,
Because the amount of file data is too large, so you only want to dserialize the part of XML you need, the purpose is to reduce memory consumption and improve efficiency?

**Comment by dudiao** [comment]
@zeshuai007 yes, I often come across an xml file several G sizes

@joehni Once I parsed an 8G xml file, a total of more than one million data, so I want to insert the database while parsing.

thanks

**Comment by joehni** [comment]
As said, with my approach you would only keep the interesting part, but yes, those are still in memory.

My next solution depends on the fact that all the objects you want to deserialize are children of the root element and you may filter the unmarshaling process on your own for those elements by overloading _unmarshal_. Here is the relevant part:

```java
final List<String> elementNames = Arrays.asList("Person");
XStream xstream = new XStream() {
  public <T> T unmarshal(HierarchicalStreamReader reader, T root, DataHolder dataHolder) {
    return elementNames.contains(reader.getNodeName) ? super.unmarshal(reader, root, dataHolder) : null;
  }
}
```

The _readObject()_ call of your code above will now deliver _null_ for any child element to ignore.

**Comment by zeshuai007** [comment]
Hi,
I simply verified the second solution of joehni, which is very good, can decode the part of Person you want
Code:
```

```
But I'm sorry, I don't have more than 1 G xml file locally, so I can't verify extreme performance scenarios. If you have solved it, please ignore me.

**Comment by zeshuai007** [comment]
Hi @joehni ,
Do you consider adding this use case to Xstreamer, this seems like a nice feature.

**Comment by joehni** [comment]
I already added an acceptance test in b275132a.
