### ISSUE TITLE
how to disable the default element-field mapping and only use mapping of annotations? 

### ISSUE THREAD

**Issue by gengyuanzhe** [x-stream/xstream#199]
I have a problem here with running the following code.
``` java
@XStreamAlias("icon")
@Builder
@Data
public class IconNode {
    @XStreamAlias("carrier-id")
    @XStreamAsAttribute
    private String carrierId;

    public static void main(String[] args) {
        XStream xstream = new XStream();
        xstream.processAnnotations(IconNode.class);
        xstream.addPermission(AnyTypePermission.ANY);

        String s = "<icon carrierId=\"101\"/>";
        IconNode icon =  xstream.fromXML(s);
        System.out.println(icon);
    }
}
```
The result is `IconNode(carrierId=101)`. But the result I expected shoud be `IconNode(carrierId=null)`. When I use annotation, I want the default **element to fied** mapping being disabled. Is there any way to do that?

**Comment by zeshuai007** [comment]
Hi @gengyuanzhe ,
If you only want to use "carrier-id" as an alias, please remove @XStreamAsAttribute because the 'carrierId' field will be serialized as an attribute.

**Comment by gengyuanzhe** [comment]
> Hi @gengyuanzhe ,
> If you only want to use "carrier-id" as an alias, please remove @XStreamAsAttribute because the 'carrierId' field will be serialized as an attribute.
@zeshuai007 
Thanks for reply, but I want `<icon carrier-id="101"/>` to be parsed as `IconNode(carrierId=101)`, and `<icon carrierId="101"/>` to be parsed as `IconNode(carrierId=null)`. Because in my project, we treat `carrier-id` as a correct attribute, but `carrierId` not, so the latter should not affect the unserialized object.

**Comment by zeshuai007** [comment]
Sorry, I misunderstood, but I have a question, if serialized by alias "carrier-id", xml will not generate "carrierId" (the attribute you think is wrong).

**Comment by gengyuanzhe** [comment]
The XML is not generated by the above code, but is constructed by the customer directly by hand or by some tools uncontrolled. Our program has serious historical baggage, and the structure of the xml is very complex, so we need to consider some attribute misinput scenarios. We should skip the misinput attribute (skip unsupported attribute **carrierId**, and the bean `carrierId` will be null), instead of mapping it to a bean field based on the default mapping strategy. This is what we promised to the interface invoker.

**Comment by joehni** [comment]
Hi,

this scenario is unfortunately not really supported. The problem is, that XStream tries to map at deserialization time the current tag or attribute name to some valid field. An alias is only used if the current name **matches** it, otherwise it looks for a direct field name. It is a valid scenario to define multiple aliases for one field to gain backwards compatibility.

What you can do though, is to define an additional alias for the real field name to a non-existing field and omit that:

```java
xstream.aliasAttribute("carrierId", "doesNotExist");
xstream.omitField(IconNode.class, "doesNotExist");
```
