### ISSUE TITLE
Serialize than deserialize an array with all possible chars fails with StaxDriver

### ISSUE THREAD

**Issue by cdanielw** [x-stream/xstream#20]
It works with the default driver. It's not really a typical use-case though - it popped up when I generated some random test data.

        char[] chars = new char[(int) Character.MAX_VALUE];
        for (int i = 0; i < chars.length; i++)
            chars[i] = (char) i;
        XStream xstream = new XStream(new StaxDriver());
        // XStream xstream = new XStream(); // This works
        String serialized = xstream.toXML(chars);
        char[] deserialized = (char[]) xstream.fromXML(serialized);
        System.out.println(Arrays.equals(chars, deserialized));

**Comment by joehni** [comment]
Not every character is valid in XML, it depends even on the XML version. And not all XML writers do check for valididity of the generated XML. See FAQ:
 - http://x-stream.github.io/faq.html#XML_null_char
 - http://x-stream.github.io/faq.html#XML_control_char

You can configure XStream's PrettyPrintWriter to make the checks, too.
