### ISSUE TITLE
Xstream not support Java 14 fully - Illegal reflective access by com.thoughtworks.xstream.core.util.Fields

### ISSUE THREAD

**Issue by donhuvy** [x-stream/xstream#202]
Warning

> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/C:/Users/MinhPhuc/.m2/repository/com/thoughtworks/xstream/xstream/1.4.11.1/xstream-1.4.11.1.jar) to field java.util.TreeMap.comparator
> WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release

**Comment by joehni** [comment]
#101
