### ISSUE TITLE
Duplicate error

### ISSUE THREAD

**Issue by MadRatSRP** [x-stream/xstream#208]
Duplicate class org.xmlpull.v1.XmlPullParser found in modules jetified-xmlpull-1.1.3.1.jar (xmlpull:xmlpull:1.1.3.1) and jetified-xpp3_min-1.1.4c.jar (xpp3:xpp3_min:1.1.4c)
Duplicate class org.xmlpull.v1.XmlPullParserException found in modules jetified-xmlpull-1.1.3.1.jar (xmlpull:xmlpull:1.1.3.1) and jetified-xpp3_min-1.1.4c.jar (xpp3:xpp3_min:1.1.4c)

Using latest version of xstream

**Comment by joehni** [comment]
XStream developers are neither invloved in development of Xpp3 nor XmlPull.

**Comment by MadRatSRP** [comment]
What do you mean? I added your library as a dependency to my build.gradle file and now it says about duplicate libraries. I didnt add neither xmlpull nor xpp3 to my project, only your library

**Comment by joehni** [comment]
XStream uses an XmlPullParser by default and Xpp3 is used as default implementation, but we do not control the Xpp3 library that includes part of the XmlPullParser API. If it bother you, you can either use Xpp3Driver directly and omit the dependency to the XmlPullParser API or use a complete different XML driver.
