### ISSUE TITLE
CompositeClassLoader is inappropriately using reflection for methods it has access to

### ISSUE THREAD

**Issue by gorky** [x-stream/xstream#214]
com.thoughtworks.xstream.core.util.CompositeClassLoader is using reflection inappropriately in it's initializer to access methods that it already have access to (if present).

**Comment by joehni** [comment]
That was simply a relict from Java 1.4 compatibility.

**Comment by gorky** [comment]
I thought that might have been the case.  It showed up in the deprecation scans with a flag for review, so that's why I had a look.  Delighted that you found this submission acceptable.
