### ISSUE TITLE
Is com.thoughtworks.xstream.core.util public api?

### ISSUE THREAD

**Issue by aclemons** [x-stream/xstream#219]
Looking at the javadocs and osgi bundle exports, it looks like this package is not part of the public API of xstream.

Spring OXM is however directly referencing CompositeClassLoader [here](https://github.com/spring-projects/spring-framework/blob/v5.2.8.RELEASE/spring-oxm/src/main/java/org/springframework/oxm/xstream/XStreamMarshaller.java#L189). I'm using spring with servicemix which includes osgi metadata for the spring bundles and it includes an optional import on this package which it not fulfilled. Using XStreamMarshaller there is not possible because CompositeClassLoader cannot be found.

If this code should not be used by client code, I'll close this and open an issue for the Spring project. Thanks.

**Comment by joehni** [comment]
Yes, the package com.thoughtworks.xstream.core.util is not part of the public API. We might add a JVM.createDefaultClassLoader() method to create such an instance, but the CompositeClassLoader itself should not be used directly outside XStream. We do not guarantee any API compatibility of that package.

However, what worries me more is the lack of support for [XStream's security framework](http://x-stream.github.io/security.html#framework).
