### ISSUE TITLE
Conflict with popular tool:  Mybatis-Plus

### ISSUE THREAD

**Issue by ukhack** [x-stream/xstream#224]
both inject mapper.

## Error:
`org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'mapper' for bean class [com.thoughtworks.xstream.mapper.Mapper] conflicts with existing, non-compatible bean definition of same name and class [com.baomidou.mybatisplus.core.mapper.Mapper]
`

**Comment by ukhack** [comment]
@Repository(value = "xmapper")  to replace default name
would be better?

**Comment by joehni** [comment]
XStream is neither involved in development of Spring nor in myBatis, it does not define such annotations at all.
