### ISSUE TITLE
XmlFriendlyNameCoder behaviour change 1.4.11.1 to 1.4.14

### ISSUE THREAD

**Issue by sopgreg** [x-stream/xstream#226]
Hi,

we recently updated the dependency from 1.4.11.1 to 1.4.14 and now have issues with one unit test. What happens now is, that the `XmlFriendlyNameCoder` replaces the `'9'` char and the unit test from our (forked) smooks library fails.

`isXmlNameChar('9')` returns `false`, which previously returned `true`. Is this the correct behaviour?

Result from the unit test is (see the 9 from 619 being replaced):

`[different] Expected element tag name 'org.milyn.javabean.JIRA.MILYN__619.RootObject' but was 'org.milyn.javabean.JIRA.MILYN__61_.0039.RootObject'`

![grafik](https://user-images.githubusercontent.com/33895520/100875404-41e9f800-34a6-11eb-9479-20ea4335c436.png)

**Comment by problemzebra2** [comment]
I guess that this is a bug caused by:

![bug](https://user-images.githubusercontent.com/46046993/100899824-84b9c900-34c2-11eb-9a1d-d884a247b815.PNG)

**Comment by joehni** [comment]
Thanks for heads-up. Stupid mistake.

**Comment by sopgreg** [comment]
Thanks for the quick fix, is there an ETA for the patch release? We need the 1.14 release because of the CVE fixed there.

**Comment by joehni** [comment]
Actually I already wait for another CVE number and have to request a 3rd one. As soon I have those two numbers, I will create a new release.
