### ISSUE TITLE
Deserialisation failed with PureJavaReflectionProvider for custom read/writeObject

### ISSUE THREAD

**Issue by UKreher** [x-stream/xstream#233]
With the XStream 1.4.14 (and older versions), the PureJavaReflectionProvider has problems deserialising an object with custom readObject()/writeObject() that does not use defaultReadObject()/defaultWriteObject().
Serialisation produces the same XML as the SunUnsafeReflectionProvider (which is fine and intended), but deserialisation fails with an IOException.

Just execute the attached class [XStreamTest.java.txt](https://github.com/x-stream/xstream/files/5678023/XStreamTest.java.txt) (with all XStream libraries in the classpath).

**Comment by joehni** [comment]
The PureJavaReflectionConverter has to rely on Java serialization which does not work for your type, because it has no default constructor. It has nothing to do with the serialization methods.

**Comment by UKreher** [comment]
You are absolutely right. The example was too simple. Sorry.

The class has a non-serialisable superclass with an accessible no-arg constructor (see [XStreamTest.java.2.txt](https://github.com/x-stream/xstream/files/5687606/XStreamTest.java.2.txt)). Java serialisation works but the PureJavaReflectionConverter does not.

**Comment by joehni** [comment]
This was actually a limitation with the strategy used to create such objects with non-serializable parents with pure JDK functionality. However, a different possibility is known by now and that one works perfectly. Thanks for the report.
