### ISSUE TITLE
Faulty optimization in #226

### ISSUE THREAD

**Issue by erilor** [x-stream/xstream#237]
#226 When this was implemented I think there was a mistake in the optimization part of encodeName in XmlFriendlyNameCoder:
```java
for (; i < length; i++) {
    final char c = name.charAt(i);
    if (c < 'A' || (c > 'Z' && c < 'a') || c > 'Z') {
        break;
    }
}
```
The last Z should probably be lower case, otherwise all lower case characters will trigger full processing.
Even with the fix this change will trigger full processing in more cases than the previous implementation, but perhaps that was intended? If so it could be a good idea to mention the change in the release notes since it will change the xml output in some cases (I noticed it on the brackets '[' of an array).

(I added a comment on the original commit and then realized I should probably create an issue, sorry about the "double reporting").

**Comment by joehni** [comment]
Thanks for the heads-up. However, if you had formerly a bracket in tag or attribute name, you had technically no longer XML, because it is not valid. A normal XML parser would reject such an input.

**Comment by erilor** [comment]
Thanks for the quick fix! I did suspect the other change was intended.
