### ISSUE TITLE
com.thoughtworks.xstream.converters.ConversionException: Invalid reference

### ISSUE THREAD

**Issue by vallamsd** [x-stream/xstream#239]
```
<capitalAssetBuilderOriginIndicator>false</capitalAssetBuilderOriginIndicator>
  <assetSharedDetails>
<org.kuali.kfs.module.cam.businessobject.AssetGlobalDetail>
        <assetGlobalUniqueDetails/>
        <newCollectionRecord>false</newCollectionRecord>
      </org.kuali.kfs.module.cam.businessobject.AssetGlobalDetail>
</assetSharedDetails>
  <assetPaymentDetails>
<org.kuali.kfs.module.cam.businessobject.AssetPaymentDetail>
        <transferPaymentIndicator>false</transferPaymentIndicator>
        <amount>
          <value>0.00</value>
        </amount>
        <postingYear>2012</postingYear>
        <overrideCode>NONE</overrideCode>
        <newCollectionRecord>false</newCollectionRecord>
      </org.kuali.kfs.module.cam.businessobject.AssetPaymentDetail>
</assetPaymentDetails>
  <separateSourceTotalAmount reference="../assetPaymentDetails/org.apache.ojb.broker.core.proxy.ListProxyDefaultImpl/org.kuali.kfs.module.cam.businessobject.AssetPaymentDetail/amount"/>
  <newCollectionRecord>false</newCollectionRecord>
</org.kuali.kfs.module.cam.businessobject.AssetGlobal>
<maintenanceAction>New</maintenanceAction>
```

------------------------------------------ Debugging information -------------------------------------------------------------
message             : Invalid reference
reference           : ../assetPaymentDetails/org.apache.ojb.broker.core.proxy.ListProxyDefaultImpl/org.kuali.kfs.module.cam.businessobject.AssetPaymentDetail/amount
referenced-type     : org.kuali.rice.core.api.util.type.KualiDecimal
referenceable       : true
class               : org.kuali.kfs.module.cam.businessobject.AssetGlobal
required-type       : org.kuali.kfs.module.cam.businessobject.AssetGlobal
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
path                : /org.kuali.kfs.module.cam.businessobject.AssetGlobal/separateSourceTotalAmount
line number         : 28
version             : 1.4.10

------------------------------------------------------ Our xstream Object instantiation------------------------------------
	```
xstream = new XStream() {
    		
    		@Override
    		 public ReflectionProvider getReflectionProvider() {
    			 return new ProxyAwareJavaReflectionProvider();
    		 }
    		 protected MapperWrapper wrapMapper(MapperWrapper next) {
    			 return new MapperWrapper(next) {
     	            public boolean isReferenceable(final Class type) {
     	                if (type == KualiDecimal.class) {
     	                    return true;
     	                } else {
     	                    return super.isReferenceable(type);
     	                }
     	            }
     	        };  		 
    	};
    	};
    	xstream.registerConverter(new ProxyConverter(xstream.getMapper(), xstream.getReflectionProvider()));
    	try {
    		  xstream.addDefaultImplementation(ArrayList.class, ListProxyDefaultImpl.class);
    	} catch ( Exception ex ) {
    	// Do nothing - this will blow if the OJB class does not exist, which it won't in some installs
    	}
		xstream.registerConverter(new DateTimeConverter());
```

**Comment by joehni** [comment]
Well, and what is wrong with this message? The reference does obviously not exists. assetPaymentDetails has no child org.apache.ojb.broker.core.proxy.ListProxyDefaultImpl.

**Comment by vallamsd** [comment]
I was referring to https://github.com/x-stream/xstream/issues/150 and completely ignored to check the path.

**Comment by joehni** [comment]
Apart from that, XStream does not claim KualiDecimal to be immutable by itself. I'd guess, your ProxyAwareJavaReflectionProvider has room for improvement. The code to handle references is not trivial.

**Comment by vallamsd** [comment]
My Initial code looks like this 
`   xstream = new XStream(new ProxyAwareJavaReflectionProvider());
        xstream.registerConverter(new ProxyConverter(xstream.getMapper(), xstream.getReflectionProvider()));
        xstream.addDefaultImplementation(ArrayList.class, ListProxyDefaultImpl.class);
        xstream.addImmutableType(KualiDecimal.class, true);
        xstream.registerConverter(new DateTimeConverter());`
------------------------------------------------------------------------------------------------------------------------------
The above code works for few documents the **separateSourceTotalAmount** can reference the amount and **assetPaymentDetails** is a type of List and has attribute class=**org.apache.ojb.broker.core.proxy.ListProxyDefaultImpl**
However, for few documents like above one the attribute is not showing. Not sure if I'm missing any configuration.

`<assetPaymentDetails class="org.apache.ojb.broker.core.proxy.ListProxyDefaultImpl">
    <org.kuali.kfs.module.cam.businessobject.AssetPaymentDetail>
      <expenditureFinancialSystemOriginationCode>MF</expenditureFinancialSystemOriginationCode>
      <expenditureFinancialDocumentPostedDate>2011-10-31</expenditureFinancialDocumentPostedDate>
      <transferPaymentIndicator>false</transferPaymentIndicator>
      <expenditureFinancialDocumentNumber>383710-29</expenditureFinancialDocumentNumber>
      <expenditureFinancialDocumentTypeCode>PRJE</expenditureFinancialDocumentTypeCode>
      <postingPeriodCode>04</postingPeriodCode>
      <amount>
        <value>9300.00</value>
      </amount>
      <documentNumber>1578071</documentNumber>
      <sequenceNumber>1</sequenceNumber>
      <postingYear>2012</postingYear>
      <overrideCode>NONE</overrideCode>
      <accountExpiredOverride>false</accountExpiredOverride>
      <accountExpiredOverrideNeeded>false</accountExpiredOverrideNeeded>
      <nonFringeAccountOverride>false</nonFringeAccountOverride>
      <nonFringeAccountOverrideNeeded>false</nonFringeAccountOverrideNeeded>
      <objectBudgetOverride>false</objectBudgetOverride>
      <objectBudgetOverrideNeeded>false</objectBudgetOverrideNeeded>
      <financialDocumentLineTypeCode>F</financialDocumentLineTypeCode>
      <salesTaxRequired>false</salesTaxRequired>
      <chartOfAccountsCode>CO</chartOfAccountsCode>
      <accountNumber>2100100</accountNumber>
      <financialObjectCode>8210</financialObjectCode>
      <versionNumber>2</versionNumber>
      <objectId>61CB9009-73DC-310E-0ABF-BEB848C220E6</objectId>
      <newCollectionRecord>false</newCollectionRecord>
    </org.kuali.kfs.module.cam.businessobject.AssetPaymentDetail>
  </assetPaymentDetails>
  <separateSourceTotalAmount>
    <value>0.00</value>
  </separateSourceTotalAmount>`

-----------------------------------------------------------------------------------------------------------------
` <assetPaymentDetails>
<org.kuali.kfs.module.cam.businessobject.AssetPaymentDetail>
        <transferPaymentIndicator>false</transferPaymentIndicator>
        <amount>
          <value>0.00</value>
        </amount>
        <postingYear>2012</postingYear>
        <overrideCode>NONE</overrideCode>
        <newCollectionRecord>false</newCollectionRecord>
      </org.kuali.kfs.module.cam.businessobject.AssetPaymentDetail>
</assetPaymentDetails>
  <separateSourceTotalAmount reference="../assetPaymentDetails/org.apache.ojb.broker.core.proxy.ListProxyDefaultImpl/org.kuali.kfs.module.cam.businessobject.AssetPaymentDetail/amount"/>`

------------------------------------------------------------------------------------------------------------------------------
`	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:58) ~[xstream-1.4.10.jar:1.4.10]
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66) ~[xstream-1.4.10.jar:1.4.10]
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:503) ~[xstream-1.4.10.jar:1.4.10]
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:429) ~[xstream-1.4.10.jar:1.4.10]
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:281) ~[xstream-1.4.10.jar:1.4.10]
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72) ~[xstream-1.4.10.jar:1.4.10]
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:70) ~[xstream-1.4.10.jar:1.4.10]
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66) ~[xstream-1.4.10.jar:1.4.10]
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50) ~[xstream-1.4.10.jar:1.4.10]
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134) ~[xstream-1.4.10.jar:1.4.10]
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32) ~[xstream-1.4.10.jar:1.4.10]
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1486) ~[xstream-1.4.10.jar:1.4.10]
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1466) ~[xstream-1.4.10.jar:1.4.10]
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1337) ~[xstream-1.4.10.jar:1.4.10]
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1328) ~[xstream-1.4.10.jar:1.4.10]
	at org.kuali.kfs.krad.service.impl.XmlObjectSerializerServiceImpl.fromXml(XmlObjectSerializerServiceImpl.java:117) ~[classes/:?]
`

**Comment by joehni** [comment]
1. Reference and class attributes do not have something to do with each other. Both attributes have a completely different purpose.
2. According the code you use to initialize XStream in the original issue description, you may or may not register ListProxyDefaultImpl as default implementation for a for List. Therefore you may or may not write the class attribute for a list. And at deserialization time you may or may not get a ListProxyDefaultImpl as the list implementation. However if you read XML that was written with a differently configured XStream at serialization time, the result might not be what you expect.
3. As already said, the code to generate the references is not trivial. And is is the task of the reflection-based converter to identify and register immutable objects and write these references. However, ProxyAwareJavaReflectionProvider is no class of XStream and I have no idea what it does. All **I** can say is, that XStream will never ever use an attribute's value as part of a reference. It does not make sense.
