### ISSUE TITLE
Getting UnknownFieldException intermittently

### ISSUE THREAD

**Issue by bansalrohit90** [x-stream/xstream#241]
Reference : com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$UnknownFieldException
LibVersion: 1.14.10

We have an extra field in a String XML and while parsing it to a java POJO, we are seeing the exception. Same lib version 2 different servers behave differently.

Server 1 - Exception thrown.
Server 2 - No Exception

Server 2 after a restart - Exception thrown

**Comment by joehni** [comment]
How do you initialize the XStream instance?

**Comment by bansalrohit90** [comment]
Found the bug, something to do with parallel processing by 2 different threads at our end. Thanks for your comment. Closing the issue,.
