### ISSUE TITLE
execute test case failed, junit.framework.ComparisonFailure	at com.thoughtworks.acceptance.QNameMappedConcreteClassesTest.testUsingDefaultNamespace(QNameMappedConcreteClassesTest.java:65)

### ISSUE THREAD

**Issue by janksenhu** [x-stream/xstream#242]
envrionment:
mac os 10.15.7
jdk 13.0.2
maven 3.6.3

execute test case failed

junit.framework.ComparisonFailure: expected:<...encoding='UTF-8'?><w[:withList xmlns:w="java://com.thoughtworks.acceptance.someobjects"><things/></w:]withList>> but was:<...encoding='UTF-8'?><w[ithList xmlns="java://com.thoughtworks.acceptance.someobjects"><things/></]withList>>
	at com.thoughtworks.acceptance.QNameMappedConcreteClassesTest.testUsingDefaultNamespace(QNameMappedConcreteClassesTest.java:65)

**Comment by joehni** [comment]
Your report does not make sense. You claim, that the test _testUsingDefaultNamespace_ from the class _com.thoughtworks.acceptance.QNameMappedConcreteClassesTest_ fails, but the error message shows that the expected string is from a different test case: testUsingNamespace.

**Comment by janksenhu** [comment]
will works fine, i find the test case need modified as bellow:

public void testUsingDefaultNamespace() {
        qnameMap.setDefaultNamespace(namespace);
        qnameMap.setDefaultPrefix("w");
        final QName qname = new QName(namespace, "withList", "w");
        qnameMap.registerMapping(qname, WithList.class);

        final WithList<?> withList = new WithList<>();
        withList.things = new ArrayList<>();

        final String expected = XML_HEADER
            + "<w:withList xmlns:w=\"java://com.thoughtworks.acceptance.someobjects\">"
            + /**/ "<w:things/>"
            + "</w:withList>";

        assertBothWays(withList, expected);
    }


====master old code as  @bellow=======

public void testUsingDefaultNamespace() {
        qnameMap.setDefaultNamespace(namespace);
        xstream.alias("withList", WithList.class);

        final WithList<?> withList = new WithList<>();
        withList.things = new ArrayList<>();

        final String expected = XML_HEADER
            + "<withList xmlns=\"java://com.thoughtworks.acceptance.someobjects\">"
            + /**/ "<things/>"
            + "</withList>";

        assertBothWays(withList, expected);
    }

**Comment by janksenhu** [comment]
> Your report does not make sense. You claim, that the test _testUsingDefaultNamespace_ from the class _com.thoughtworks.acceptance.QNameMappedConcreteClassesTest_ fails, but the error message shows that the expected string is from a different test case: testUsingNamespace.


the master branch ,test case QNameMappedConcreteClassesTest.java testUsingDefaultNamespace method add three lines will works fine


qnameMap.setDefaultPrefix("w");
final QName qname = new QName(namespace, "withList", "w");
qnameMap.registerMapping(qname, WithList.class);

**Comment by joehni** [comment]
Sorry, but Java 13 works fine as is, see [Travis](https://travis-ci.org/github/x-stream/xstream/builds/753268056). And even worse, your modification is a wrong implementation of this test (testUsingDefaultNamespace), because it should exactly test the behaviour for the default namespace. If you set a prefix, it is no longer the default namespace and the test is useless.

I can't say, what is wrong in your environment, I have no access to MacOS.
