### ISSUE TITLE
New security issues in 1.4.16

### ISSUE THREAD

**Issue by cax21** [x-stream/xstream#243]
hi,
since the upgrade to 1.4.16, looks like xstream has a dependency on mxparser-1.2.1,
which in turn brings loads of security issues.

![image](https://user-images.githubusercontent.com/32536771/112637290-457f0180-8e3e-11eb-9db4-c24ecda0c60e.png)

any chance to have those critical vulnerabilities fixed ?

thank you

**Comment by joehni** [comment]
This is simply bullshit! These are reported CVEs for XStream:
https://x-stream.github.io/security.html#CVEs

What should they have to do with MXParser? It any tool generates such a report, go and fix the tool.

Regards,
Jörg
