### ISSUE TITLE
xtream 1.4.3 and openjdk CentOS 7 package 1.0.8.282

### ISSUE THREAD

**Issue by ariegugu** [x-stream/xstream#248]
Hi,

let me state first that I am not a java developer but a system administrator. That said: an internal application uses xstream 1.4.3. Yesterday we tried to update openjdk (CentOS 7 base package) from 1.8.0.262 to 1.8.0.282, a minor upgrade. Our application ceased to work, logging:

com.thoughtworks.xstream.converters.ConversionException: Cannot construct my.domain.operations.commons.model.StandardSearchClause as it does not have a no-args constructor : Cannot construct my.domain.operations.commons.model.StandardSearchClause as it does not have a no-args constructor
---- Debugging information ----
message             : Cannot construct my.domain.operations.commons.model.StandardSearchClause as it does not have a no-args constructor
cause-exception     : com.thoughtworks.xstream.converters.reflection.ObjectAccessException
cause-message       : Cannot construct my.domain.operations.commons.model.StandardSearchClause as it does not have a no-args constructor
class               : my.domain.operations.commons.model.StandardSearchClause
required-type       : my.domain.operations.commons.model.StandardSearchClause
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
line number         : 1
class[1]            : java.util.ArrayList
converter-type[1]   : com.thoughtworks.xstream.converters.collections.CollectionConverter
class[2]            : my.domain.operations.commons.model.StandardSearchCriteria
version             : null
-------------------------------
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)

We stepped back to 1.8.0.262 and it worked again. We will now hold the openjdk update in our yum.conf, but of course we would like to be able to update in the near future.

Has anyone experienced this compatibility issue as well? Should we upgrade xstream to the latest 1.4? We would like to avoid the latter because that might bring up other compatibility issues...

Thanks and best regards,
Arjen Van Drie.

**Comment by joehni** [comment]
It simply means that XStream no longer recognizes this JDK as fully supported and uses by default the pure Java mode now. Compare the output of
```bash
java -cp xstream-1.4.3.jar com.thoughtworks.xstream.core.JVM
```
using the different JDKs.

XStream 1.4.3 is nearly 9 years old and has several open security issues. The 1.4.x product line is supposed to be upgrade binary compatible, except that the latest versions block now class types that can be used to inject malicious stuff into the process unmarshalling the XML. However, the blocked types are normally never part of an XML serialization in real world applications. If an application really breaks, it might have security problems as well.
