### ISSUE TITLE
New Xstream doesn't parse <? sections after 1.4.15

### ISSUE THREAD

**Issue by AmitAmar** [x-stream/xstream#258]
I'm using xstream version 1.4.15 and I'm trying to upgrade to version: 1.4.17 without success.

The reason of failure is because I have files that contains <?ignore ....... ->

that contains -- (multiple times the character '-')

The parser doesn't ignore it. In Xstrean version 1.4.15 it works great.

I got this execption:

XmlPullParserException: processing instruction started on line 20 and column 5 was not closed (position: END_TAG seen ...\t\t+---------->| Entered Assigned Unit\t|-------------------------->... @48:88)

How I can solve this issue and ignore this "<?ignore" section?

Thank you very much and have a nice day,

Amit.

**Comment by joehni** [comment]
This has nothing to do with XStream itself, just with the XML parser in use. Simply switch the parser. For XStream 1.4.17 exclude the dependency to the MXParser and add one to the Xpp3 parser again.
