### ISSUE TITLE
Vulnerability in Xstream Version 1.4.17

### ISSUE THREAD

**Issue by raptorshots** [x-stream/xstream#261]
One of our Security Tools (JFrog Xray) flagged 1.4.17 version as vulnerable sourced from Below Vulnerability Database 

Details : https://vul.wangan.com/a/CNVD-2021-40248 (You might need to translate)

There is no much details in the link, but is this a confirmed vulnerability?

**Comment by joehni** [comment]
Can't say, I cannot read Chinese. I have new reports for security issues, maybe those report covers one of it. All reported issued have been verified and CVE reports have been written, but I have not all of them reported to get the CVE number. This depends simply on my spare time for the project.

However, all reports are based on stuff in the Java runtime which is not on the default blacklist of XStream 1.4.17. Therefore use a whitelist with XStream 1.4.17 and you will have no issue. With 1.4.18 you will have to use the whitelist anyway unless you explicitly set your own blacklist - with all known consequences.
