### ISSUE TITLE
Invalid references when deserializing

### ISSUE THREAD

**Issue by jvbrandis** [x-stream/xstream#269]
We are running into an issue where the serializing instance of XStream is using a newer version of a class, where a new field has been added. This new field is of the same type as another existing field, so if the object of those two fields are the same, XStream will reference the previous object for performance.

By the order of encoding, XStream will fully encode the NEW field, while the "legacy" field is referencing the new field.

```
package test;

public class TestMessage {

  final SubClass field1;
  final SubClass field2; //this field is new

  public TestMessage(SubClass field1, SubClass field2) {
    this.field1 = field1;
    this.field2 = field2;
  }

  public static class SubClass {
    final String field;
    public SubClass(String field) {
      this.field = field;
    }
  }
}
```

The code for encoding XML:

```
    Xpp3Driver driver = new Xpp3Driver();
    XStream encodingXstream = new XStream(driver);

    //create a single subclass object
    TestMessage.SubClass sub = new TestMessage.SubClass("abc");

    //use the same object both for field1 and field2, so xstream will reference field1 when encoding field2
    TestMessage obj = new TestMessage(sub, sub);

    ByteArrayOutputStream baos = new ByteArrayOutputStream();
    encodingXstream.marshal(obj, driver.createWriter(baos));
    System.out.println(new String(baos.toByteArray()));

```
The resulting XML:

```
<test.TestMessage>
  <field1>
    <field>abc</field>
  </field1>
  <field2 reference="../field1"/>
</test.TestMessage>

```

The new field is ignored in the deserializing XStream instance, as we are using the .ignoreUnknownElements() option.
However, since the field2 is referencing field1, the deserialization fails even if ignoreUnknownElemens() is set.

Therefore, this code fails when decoding with the following code, when TestMessage.field1 is commented out:

```
 //before executing this test, please comment out "field1" in TestMessage.java

    Xpp3Driver driver = new Xpp3Driver();
    XStream decodingXstream = new XStream(driver);
    decodingXstream.addPermission(NoTypePermission.NONE);
    decodingXstream.addPermission(PrimitiveTypePermission.PRIMITIVES);
    decodingXstream.addPermission(NullPermission.NULL);
    decodingXstream.allowTypes(new Class[]{TestMessage.class});
    decodingXstream.allowTypes(new Class[]{TestMessage.SubClass.class});
    decodingXstream.ignoreUnknownElements();

    String xml = "<test.TestMessage>\n" +
            "  <field1>\n" +
            "    <field>abc</field>\n" +
            "  </field1>\n" +
            "  <field2 reference=\"../field1\"/>\n" +
            "</test.TestMessage>";

    //this fails with "Invalid reference" when deserializing
    TestMessage msg = (TestMessage) decodingXstream.unmarshal(driver.createReader(new StringReader(xml)));
    assertNull(msg.field2);
```

In my opinion, referencing an unknown field should have the same behaviour as being an unknown field

**Comment by joehni** [comment]
> XStream will reference the previous object for performance.

This is wrong. Your object graph contains one instance of the type and XStream tries very hard to accomplish the same after unmarshalling. This has nothing to do with performance. If you want multiple instances, you may set the Subclass type to immutable.

You can also configure XStream to omit the new field (or declare it as transient), then you can handle the situation by setting the new field in an readResolve method of TestMessage. Then the XML produced from the new type is the same as before.

However, from your description I assume, you expect the application that contains the old class type should deal with the new XML format just by ignoring the new field independently if it is a reference or not.

> In my opinion, referencing an unknown field should have the same behaviour as being an unknown field

For me it does. See 238d68de7fe4e3cdb95e2ed8d730aa3548c56b90. The last test proofes it.

So, which version of XStream you're using?

**Comment by jvbrandis** [comment]
Hi Jorg!
We are currently using XStream 1.4.16.

Your test is slightly different than my use case.
Changing the expectedXML in testReferencedElementsCanBeIgnored() to the following will trigger the error.

```
final String expectedXml = ""
            + "<wrapper>\n"
            + "  <member2>\n"
            + "    <name>junit</name>\n"
            + "  </member2>\n"
            + "  <member reference=\"../member\"/>\n"
            + "</wrapper>";
```

Since we are not micromanaging every field and class in our XStream setup, chance has it that member2 (in our case) was the new field, while "member" was the existing field. However, the order of encoding causes XStream to encode "our" member2-field first, which makes the _new_ field ignored, while the _old_ field is referencing the ignored field.

**Comment by joehni** [comment]
This cannot work. The old class has no member "member2", therefore XStream does not know, what to to with it. You configured it to skip the element - fine. However, since XStream cannot know what this elements is at all, it cannot generate an object that can be referenced later on - no way.

If you care for backward compatibility, you have to micromanage some stuff. I don't know of any other serialization library that could handle such an situation out-of-the-box either.

Do you have the possibility to modify the old application's classes? Then you could add a helper class (here Wrapper2) that converts the data of the new structure into the old class type:

```java
    static public class Wrapper2 {
        public Member member2;
        private Wrapper readResolve() {
            Wrapper wrapper = new Wrapper();
            wrapper.member = member2;
            return wrapper;
        }
    }

    public void testUseReadResolve() {
        final Member member = new Member();
        member.name = "junit";
        final Wrapper wrapper = new Wrapper();
        wrapper.member = member;

        xstream.alias("wrapper", Wrapper2.class);
        xstream.ignoreUnknownElements();

        final String expectedXml = ""
            + "<wrapper>\n"
            + "  <member2>\n"
            + "    <name>junit</name>\n"
            + "  </member2>\n"
            + "  <member reference=\"../member2\"/>\n"
            + "</wrapper>";

        final Wrapper out = (Wrapper)xstream.fromXML(expectedXml);
        assertEquals("junit", out.member.name);
    }
```

**Comment by jvbrandis** [comment]
Hi Jorg.
The reason for the difference in code is basically that the deserializing code is not yet updated with the lastest model, which may happen because the application consists of a lot of distributed components, which may not be all updated at the same time.
So instead of modifying the "old code", we will simply update it to the latest version.
However, in the mean time, we would like to keep things working.

I understand that XStream cannot deserialize data from a reference to an element which does not exist.
What I am looking for here, is an **option** to make it ignore such data as if it was not sent, instead of failing with "invalid reference".
I admit that this behaviour cannot be default in any way, but in our case, that use case would be preferred over having the application fail on deserializing.

The alternative would be to disable all use of references in the sender component.

**Comment by joehni** [comment]
Well, if you want to set an option, you have to modify code and you may as well add another class.

However, if your old applications should run untouched, you have to keep the XML structure compatible in your new code. I already suggested to omit the new field and use a readResolve method in the updated class that sets the value. Adjusted to the example in the unit tests this would mean:

```java
class Wrapper {
  Member member;
  Parent parent;
  Wrapper readResolve() {
    if (member == null) // old format
      member = parent.member;
    return this;
  }
}

xstream.omitField(xstream.omitField(Wrapper.class, "member");
```

That way, old and new applications will run and when all old components are phased out, you may remove the omitField call to write and read the new format. Once the old format does no longer have to b e processed, you may even remove the readResolve method again.

**Comment by jvbrandis** [comment]
Hi Jorg! Sorry for being unclear;
we are absolutely able to update the "old" code also.
The point is that we have thousands of different objects, which are constantly evolving.
We are using XStream as a general serialization mechanism, to avoid using Java serialization, especially to have better control with which classes are allowed to deserialize.

Thus, we will run into this problem pretty often, as one part of the application will change its runtime (the code is not changing simultanously in the entire system).

That is why we are using "ignoreUnknownElements"; and I would like an "ignoreUnknownReferences" as well

**Comment by joehni** [comment]
And I already explained why "ignoreUnknownReferences" is technically impossible. You get the exception, because old components try to unmarshal with the new format and I doubt the result would improve, if an object with an invalid reference is suddenly null afterwards. If you want to mix and match such different class versions for serialization, you will have to keep the serialized format quite stable or think about a strategy to make it possible. I gave you quite some different possibilities to deal with the situation.

**Comment by jvbrandis** [comment]
Jorg; I fully understand that "ignoreUnknownReferences" would mean that an referencing an unknown field would result in dropping the reference and setting field value null. I cannot see how that is technically impossible?

And yes, that may for many users NOT improve the situation, but that should perhaps be up to the users to decide?
In our use case, that would work. I am requesting an option, not a change in default behaviour.
