### ISSUE TITLE
ForbiddenClassException

### ISSUE THREAD

**Issue by aceeric** [x-stream/xstream#275]
We have a situation where we use a third-party library (call it "lib1") that uses x-stream, and was built with x-stream 1.4.11. (It is ancient.) Our project includes another dependency that recently introduced x-stream 1.4.18. This broke lib1 with `ForbiddenClassException`. We can't really change either dependency and upgrading lib1 would be a task we haven't budgeted for.

So my question is - is there a way to override or customize the x-stream configuration via a JVM property or other JVM-wide configuration. Yes I realize this negates the very idea of x-stream security but - as I said - I'm looking for a compromise / short-term solution to an app that is used 100% in-house. Thanks.

**Comment by joehni** [comment]
Hi,

sorry, no, there's no such global configuration possibility.

if you don't care about security in this in-house application, try to downgrade to 1.4.17. Won't this work?

Regards,
Jörg

**Comment by aceeric** [comment]
Thanks - in fact that is what we did. We explicitly set the version in our parent POM. I wondered if there might be a way to do this without modifying our POM thus necessitating a re-build/re-release. So far in our testing 1.4.17 appears to be working fine though. Thanks again.
