### ISSUE TITLE
Malformed version in the source Manifest

### ISSUE THREAD

**Issue by pzi-dsa** [x-stream/xstream#277]
I'm building an Eclipse application using XStream 1.4.18 and Tycho.
The build, however, is failing with the following error:
> org.osgi.framework.BundleException: Invalid manifest header Bundle-Version: "1.4.18 Sources" : invalid version "1.4.18 Sources": non-numeric "18 Sources"

The problem is caused by the OSGi information contained in the source plugin. More specifically, the "18 Source" String is treated as the micro version, instead of just the "18".
See chapter 3.2.5 in https://osgi.github.io/osgi/core/framework.module.html#i2655136 for reference.
My suggestion is to either remove the " Sources" suffix or to specify it as a qualifier (e.g. 1.4.18.Sources).

**Comment by joehni** [comment]
Actually I never thought of an environment where the manifest of the source artifact might be checked for validity.
