### ISSUE TITLE
ClassAliasingMapper itemTypeAsAttribute never works. 

### ISSUE THREAD

**Issue by patelm5** [x-stream/xstream#28]
I'm pretty sure this can never work, whatever it's intended purpose ( I was trying to create a Shortname class mapper which still respected the aliases. )

```public boolean itemTypeAsAttribute(final Class<?> clazz) {
        return classToName.containsKey(clazz);
 }```

The keys in the map are String type.

**Comment by joehni** [comment]
Thanks for heads-up. Fortunately the method is never called, it's a left-over of an old implementation.
