### ISSUE TITLE
Attribute and Tag have the same name

### ISSUE THREAD

**Issue by wimjongman** [x-stream/xstream#281]
I have the following situation that I can't resolve:

```
<parent name="name">
  <name>name1</name>
</parent> 

```
Can you give me a hint to get this started?

**Comment by joehni** [comment]
XStream's own converters won't handle this, the attribute will always take precedence. However, You can write your own custom converter. See the converter tutorial. Just remember XStream is stream based, i.e. when your converter is called, you are in the scope of the parent tag and this is the only place where you can access the attributes. When you access the child nodes, the stream progresses and the attributes are no longer available.
