### ISSUE TITLE
Integrating xstream into oss-fuzz

### ISSUE THREAD

**Issue by vargen** [x-stream/xstream#290]
Hi all,

I have prepared the initial integration https://github.com/CodeIntelligenceTesting/oss-fuzz/commit/0456d3d63f2d3b8c6409a03357efc13a3bec7450 of xstream into [google oss-fuzz](https://github.com/google/oss-fuzz). This will enable continuous fuzzing of this project, which will be conducted by Google. Bugs that will be found by fuzzing will be reported to you. After the initial integration of this project into oss-fuzz, I will continue to add additional fuzz tests to improve the code coverage over time.

The integration requires a primary contact, someone to deal with the bug reports submitted by oss-fuzz. The email address needs to belong to an established project committer and be associated with a Google account as per [here](https://google.github.io/oss-fuzz/getting-started/accepting-new-projects/). When a bug is found, you will receive an email that will provide you with access to ClusterFuzz, crash reports, and fuzzer statistics. More than 1 person can be included. Please let me know who I should include, if anyone.

[Jazzer](https://github.com/CodeIntelligenceTesting/jazzer) is used for fuzzing Java applications. Jazzer is a coverage-guided, in-process fuzzer for the JVM platform developed by Code Intelligence. It is based on libFuzzer and brings many of its instrumentation-powered mutation features to the JVM. Jazzer has already found several bugs in JVM applications: [Jazzer Findings](https://github.com/CodeIntelligenceTesting/jazzer#findings)

Please let me know if you have any questions regarding fuzzing or the oss-fuzz integration.

**Comment by joehni** [comment]
Hi,

thanks for your offer. While it is interesting, I have currently no capacity to handle it.

**Comment by vargen** [comment]
Hi @joehni 

I just want to clarify a couple of things. I have written the initial fuzz target and will write additional ones to improve coverage. I will handle submitting the project to Google OSS Fuzz and the fuzz targets can be maintained in their repository. The emails you receive will contain stack traces and the specific inputs that triggered the bug. The only thing you will need to do is handle/fix bugs that are reported. If this still does not sound like something you are interested in, that is fine. As I said, I just wanted to make sure we were on the same page. Is there anyone else that might be able to handle the bug reports?

**Comment by joehni** [comment]
Hi @vargen,

yes I understood the offer, but real life keeps me currently from doing any OSS work.

Regards,
Jörg

**Comment by vargen** [comment]
No problem. If things change in the future, feel free to reach out to me.

**Comment by joehni** [comment]
Thanks for your understanding. I can simple reopen the issue, if I have more capacity.
