### ISSUE TITLE
ForbiddenClassException and how to avoid it  ?

### ISSUE THREAD

**Issue by Shikari0744** [x-stream/xstream#302]
**Errors :** 
```
com.thoughtworks.xstream.security.ForbiddenClassException: com.*.Status
com.thoughtworks.xstream.security.ForbiddenClassException: com.*.Entry
.
.
```
I had similar problem. I want to know how do we do a proper initialization now to avoid ForbiddenClassException, because in newer it is failing during deserialization part.

```
 Object result;
        try (Reader sr = new StringReader(xmlData)) {
            result = xStream.fromXML(sr);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        if (result == null) {
            throw new RuntimeException("ERROR: could not convert XML data to Object");
        }
        return (Status) result;
```

**Note :** I was using _1.4.17_ earlier but I want to upgrade it to _1.4.19v._

**Comment by joehni** [comment]
See the description of the [Security Framework](https://x-stream.github.io/security.html#framework) to declare the proper rules for your types.

**Comment by Shikari0744** [comment]
I looked into the [Security Framework](https://x-stream.github.io/security.html#framework) you mentioned. I have included everything like alias, implicit array in addition to that I used ExplicitTypePermission for allowing certain types but still facing same issue ForbiddenClassException, eventhough I added that class manually inside allowTypes() method.
