### ISSUE TITLE
Versión 1.4.19 que rompe JMapper con com.thoughtworks.xstream.security.ForbiddenClassException: com.googlecode.jmapper.xml.beans.XmlJmapper

### ISSUE THREAD

**Issue by luismora1224** [x-stream/xstream#305]
https://github.com/x-stream/xstream/issues/270

Hello, I have this same problem, but with version 1.4.19, I have read the comments, however I cannot understand how to implement this solution of the security framework, I am using spring boot 2.7.0, there will be some guide or manual, that explain how to do this security framework in this framework. I imagine you should create a bean, where you put the configuration of the class or classes, which can be used, but I can't understand it well, thank you very much in advance.

**Comment by joehni** [comment]
Duplicates #270
