### ISSUE TITLE
alias collection type

### ISSUE THREAD

**Issue by adjiandov** [x-stream/xstream#306]
Hello, this is a question before it becomes an issue. I have the following scenario:

`Class A  {
List<TypeA> typesA;
}
`
`Class B {
List<TypeB> typesB
}`

I am wandering if there is a way to alias the collection types with the same name and process this type of xml both marshalling and unmarshalling. So I would like to be able to produce/consume the following quasi XML structure:

`<classA>
   <typesA>
      <type></type>
      <type></type>
   </typesA>
</classA>
<classB>
   <typesB>
      <type></type>
      <type></type>
   </typesA>
</classA>
`

Where typeA and typeB would both have the same alias 'type'.

Thank you

**Comment by joehni** [comment]
Hi, you may simple define a [field alias](https://x-stream.github.io/alias-tutorial.html#field_aliasing) for both members.
