### ISSUE TITLE
Potential performance improvements to FieldDictionary from 2015 still not released

### ISSUE THREAD

**Issue by mdealer** [x-stream/xstream#312]
I am encountering major lock contention in FieldDictionary.buildMap when deserializing large XML files in parallel. I see that on master there were multiple commits to improve performance in 2015, but 1.4.19 still does not include this change.

Could someone shed some light on this?

I was analyzing a performance issue in Jenkins, so I parallelized loading a big set of big XML files and stumbled upon this. For some areas in Jenkins the FieldDictionary is part of a critical (albeit naive) path.

**Comment by joehni** [comment]
XStream 1.4.x is still compatible to Java 1.4 and my spare time only allowed me to work on reported security issues rather a new version 1.5.
