### ISSUE TITLE
Unable to serialize Oracle DB objects using xstream 

### ISSUE THREAD

**Issue by Sarthak160** [x-stream/xstream#318]
I am using xstream to  serialize ResultSet object for oracleDB but facing this kind of error -

`com.thoughtworks.xstream.converters.ConversionException: No converter specified
---- Debugging information ----
message             : No converter specified
type                : oracle.jdbc.driver.NoSupportHAManager
-------------------------------` 

Below is the example i am trying to run - 

            Statement stmt=con.createStatement();
            XStream xstream = new XStream();
            xstream.alias("Statement", Statement.class);
            xstream.ignoreUnknownElements();

            xstream.addPermission(AnyTypePermission.ANY);
            String temp = xstream.toXML(stmt);
            System.out.println(temp);

            ResultSet rs=stmt.executeQuery("select * from notes");

            while(rs.next())
                System.out.println(rs.getInt(1)+"  "+rs.getString(2)+"  "+rs.getString(3));

            con.close();

Does Xstream support serialization of Oracle objects ??

**Comment by joehni** [comment]
It does if you open the package for XStream to use reflection.

**Comment by Sarthak160** [comment]
Hi @joehni I thought xstream internally use reflection itself . Is there anything other than above which I have to do So that it can be serialized into xml/byte Array and vice versa 
Btw I used the older version of oracle db , and I was able to do that . But I have to build my app with the newer version .

**Comment by joehni** [comment]
XStream can only use reflection on this class type, if the module of the class is open. If you don't know what that means, please inform yourself about the Java module system that was introduced with Java 9.
