### ISSUE TITLE
XStreamOmitField default value

### ISSUE THREAD

**Issue by quantrpeter** [x-stream/xstream#332]
Hi
   I can use XStreamOmitField to ignore some fields to write to xml, but when I deserialise it back from xml to object, the default value is not -1. It become 0. Any hints please?

```
	@XStreamOmitField
	public int level = -1;
```

thanks
Peter

**Comment by joehni** [comment]
Hi Peter,

XStream mimics Java serialization and does indeed not call a constructor at deserialization time. See [FAQ](https://x-stream.github.io/faq.html#Serialization_no_ctor_running) for this topic.

Regards,
Jörg
