### ISSUE TITLE
Not able to deserialize inner class

### ISSUE THREAD

**Issue by nitroamos** [x-stream/xstream#34]
Here's a mockup of a class I'd like to serialize:

    import java.util.HashMap;
    public class OuterClass {
        class InnerClass extends HashMap<String, String> {
            public InnerClass(){
                put("key1","value1");
                put("key2","value2");
                put("key3","value3");
                put("key4","value4");
            }
        }
        private InnerClass field = new InnerClass();
    }

with the following XStream serialization:

        XStream xstream = new XStream(new DomDriver());
        xstream.alias("OuterClass", OuterClass.class);
        xstream.registerLocalConverter(OuterClass.class,"field",
                new NamedMapConverter(xstream.getMapper(), "property", "name",
                            String.class, null, String.class,
                            true, false, xstream.getConverterLookup()){
                        public boolean canConvert(Class type){
                            return true;
                        }
                    });
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        OuterClass myObj = new OuterClass();
        xstream.toXML(myObj,baos);
        System.out.println(baos.toString());
        ByteArrayInputStream bais = new ByteArrayInputStream(baos.toString().getBytes());
        xstream.fromXML(bais, myObj);

produces this xml when serialized as expected:

    <OuterClass>
      <field>
        <property name="key1">value1</property>
        <property name="key2">value2</property>
        <property name="key3">value3</property>
        <property name="key4">value4</property>
      </field>
    </OuterClass>

but this error when deserialized:

    com.thoughtworks.xstream.converters.ConversionException: Cannot instantiate OuterClass$InnerClass : OuterClass$InnerClass
    ---- Debugging information ----
    message             : Cannot instantiate OuterClass$InnerClass
    cause-exception     : java.lang.InstantiationException
    cause-message       : OuterClass$InnerClass
    class               : OuterClass$InnerClass
    required-type       : OuterClass$InnerClass
    converter-type      : SessionWriterTest$1
    path                : /OuterClass/field
    class[1]            : OuterClass
    converter-type[1]   : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
    version             : not available
    -------------------------------

I'm using XStream 1.4.8. If I move the inner class into its own file, then both serialization and deserialization work.

Is there a bug or am I doing something wrong?

**Comment by joehni** [comment]
Your instance of the InnerClass contains an implicit member to the instance of the OuterClass (see Java language spec). The NamedMapConverter does not handle this member and without it, it is not possible to instantiate an instance of InnerClass.

You may declare the InnerClass as static, since you do not actually use the outer instance.

**Comment by nitroamos** [comment]
Ah, I think that makes sense. I'll make it static. Thanks!
