### ISSUE TITLE
Is there any  annotations  can support both attribute and sub tags

### ISSUE THREAD

**Issue by seiyafei** [x-stream/xstream#344]
`<parms>
    <parm name="AAA">BBBBB</parm>
    <parm name="CCC">DDDDD</parm>
</parms>
`

Is there any  annotations  can support both attribute and sub tags like this?How should my class be written?

**Comment by joehni** [comment]
You can use the ToAttributedValueConverter and register it either for a specific type or as local converter. Registration of a converter can be done with annotation XStreamConverter. See unit test c.t.acceptance.annotations.ParameterizedConverterTest for examples.
