### ISSUE TITLE
Failed to use @XStreamConverter to specify converter with non-default constructor and pass equal values into constructor

### ISSUE THREAD

**Issue by emamedov** [x-stream/xstream#35]
Hi.

XStream: 1.4.8

I faced issue that is described here (http://stackoverflow.com/questions/27926281/is-it-possible-to-use-namedmapconverter-in-annotation-how). We can't use @XStreamConverter annotation to specify converter if it has non-default constructor and we want to pass into this constructor equal values for some arguments (for example, NamedMapConverter with keyAsAttribute=true and valueAsAttribute=true). Proposed in stackoverflow workaround works but it is not a good solution

**Comment by joehni** [comment]
Hi, I know there was a reason for the comparison, but I don't remember. I'll have to investigate. Basically the original poster is right, that it fails badly for two equal values, especially if you have to provide multiple booleans.
