### ISSUE TITLE
CustomObjectInputStream's readInt throws a cast error if the read data is a Byte.

### ISSUE THREAD

**Issue by thxwelchs** [x-stream/xstream#357]
https://github.com/x-stream/xstream/blob/d03f6987b793fac71ab89a31d7aa633c366c5289/xstream/src/java/com/thoughtworks/xstream/core/util/CustomObjectInputStream.java#L164

(Integer) Byte cannot be converted to an Integer when an explicit cast is attempted. I wonder why this was implemented this way.

**Comment by joehni** [comment]
Actually I don't understand the question. This is how Java Serialization works: If you have written a Byte into the object stream, you will have to read a Byte again. It will not miraculously turn into an Integer, just because your do now try read one. You broke the API contract.

**Comment by thxwelchs** [comment]
@joehni 
Thank you for your feedback. I know about the Stream API contract. But my point is that if the type read from the stream is Byte, an explicit integer conversion of ReferenceType will cause a cast error.

I think it should be modified as shown in the example, but if  I'm not understanding about this feature, please let me know.

` return ((int)peekCallback().readFromStream()); `

` return peekCallback().readFromStream().intValue(); // Convert Byte to int (auto-unboxing followed by implicit casting)`

**Comment by joehni** [comment]
Maybe you should also have a look at CustomObjectOutputStream, then you'll see, that the custom implementations of XStream will only write objects, since the representing tag (e.g. "int") in XML does not differentiate between the native and the boxed type, they are represented in the same way. However, if the method readInt() has been called, the (XML) stream must contain an Integer object, that is returned unboxed again.

**Comment by thxwelchs** [comment]
> Maybe you should also have a look at CustomObjectOutputStream, then you'll see, that the custom implementations of XStream will only write objects, since the representing tag (e.g. "int") in XML does not differentiate between the native and the boxed type, they are represented in the same way. However, if the method readInt() has been called, the (XML) stream must contain an Integer object, that is returned unboxed again.

Thanks for the detailed explanation. I understood what you were saying, that the output stream is written as an integer type rather than a byte

I faced this problem indirectly with Spring Batch, which is using XStream. SpringBatch serializes the metadata information to XStream, but it seems to do it as Byte instead of object.

**Comment by joehni** [comment]
BTW: Just using a formatter that sorts the members of a class into a different order might cause such problems...
