### ISSUE TITLE
Alias using serialization proxy pattern ?

### ISSUE THREAD

**Issue by jjazzboss** [x-stream/xstream#358]
Is there a way to alias the serialization proxy class when using the serialization proxy pattern ? 

For example in my Position class I tried aliasing its SerializationProxy:
```
xstream.alias("Position", Position.class);
xstream.alias("PositionSp", Position.SerializationProxy.class);
```

but when I save the file I still get a hard-coded class reference to the serialization proxy class (spPos is a Position field of another class) :

```
<spPos resolves-to="org.jjazz.harmony.api.Position$SerializationProxy">
    <spVERSION>1</spVERSION>
    <spPos>[0:0]</spPos>
</spPos>
```

Thanks for the help !

**Comment by jjazzboss** [comment]
Oh my mistake I was setting the alias in the wrong xstream instance, it works

**Comment by joehni** [comment]
No problem, you're welcome :)
