### ISSUE TITLE
info required for compatible version with openjdk21

### ISSUE THREAD

**Issue by sahil3390** [x-stream/xstream#361]
Hello team,

Which version of xstream is compatible with openjdk21?

Regards,
Sahil

**Comment by joehni** [comment]
Hello Sahil,

XStream is currently not fully compatible with Java 21, but as long as you don't unmarshal lambda expressions serialized with an older JDK, everything else works like in Java 17.

**Comment by joehni** [comment]
Upcoming version 1.4.21 runs all unit tests without problems.
