### ISSUE TITLE
Possible Null Pointer Dereference in AbstractJsonWriter.java

### ISSUE THREAD

**Issue by Sawraz-OpenRef** [x-stream/xstream#363]
### What happened?

In file: [AbstractJsonWriter.java](https://github.com/x-stream/xstream/blob/XSTREAM_1_4_20/xstream/src/java/com/thoughtworks/xstream/io/json/AbstractJsonWriter.java#L259), there is a potential case of null pointer dereference. In method `setValue()` inside class `AbstractJsonWriter`, there is a call to `stack.peek()`. Here `stack` is an object of class `FastStack`.
```java
    public void setValue(String text) {
        Class type = ((StackElement)stack.peek()).type;
        if ((type == Character.class || type == Character.TYPE) && "".equals(text)) {
            text = "\u0000";
        }
        handleCheckedStateTransition(STATE_SET_VALUE, null, text);
        expectedStates = STATE_NEXT_ELEMENT | STATE_ROOT;
    }
```
Then `type` field is invoked on the supposedly returned `StackElement` object, that we get after type casting the return value of `stack.peek()`. But [peek()](https://github.com/x-stream/xstream/blob/master/xstream/src/java/com/thoughtworks/xstream/core/util/FastStack.java#L56) method of class `FastStack` can return null under a certain condition, namely **`pointer=0`**.
```java
    public T peek() {
        return pointer == 0 ? null : stack[pointer - 1];
    }
```
If that happens, then it will cause a NullPointerException.

However, it is not immediately clear whether `pointer` would always be positive for `stack` in `setValue` method or not. If that is indeed the case, you may choose to ignore this issue.

### Sponsorship and Support:
This work is done by the security researchers from OpenRefactory and is supported by the [Open Source Security Foundation (OpenSSF)](https://openssf.org/): [Project Alpha-Omega](https://alpha-omega.dev/). Alpha-Omega is a project partnering with open source software project maintainers to systematically find new, as-yet-undiscovered vulnerabilities in open source code - and get them fixed - to improve global software supply chain security.

The bug is found by running the iCR tool by [OpenRefactory, Inc.](https://openrefactory.com/) and then manually triaging the results.

**Comment by joehni** [comment]
Hello,
thanks for the analysis and, yes, you're right from the plain code analysis, but not from the context. A value is never written, if you've not already started a note. So the stack will always contain at least one value if the class is used in its context.
Regards, Jörg
