### ISSUE TITLE
InitializationException eats exception of constructor called by @XStreamConverter

### ISSUE THREAD

**Issue by ge0ffrey** [x-stream/xstream#37]
We have code like this (in optaplanner.org):

    public class CloudBalance {
    
        @XStreamConverter(value = XStreamScoreConverter.class, types = {HardSoftScoreDefinition.class})
        private HardSoftScore score;
    
    }

    public class XStreamScoreConverter {
    
        public XStreamScoreConverter(Class scoreClass, Class scoreDefinitionClass) {
            if (scoreDefinitionClass.equals(HardSoftScoreDefinition.class)) { // true
                throw new IllegalStateException("Please don't eat me!!!");
            }
        }
    }

And that throws this exception:

    com.thoughtworks.xstream.InitializationException: Cannot instantiate converter ...XStreamScoreConverter for type ...HardSoftScore : Cannot construct ...XStreamScoreConverter : null

Notice that the IllegalStateException "Please don't eat me!!!" is actually eaten. Instead of being eaten, it should be wrapped as a cause:

    Caused by: ...IllegalStateException Please don't eat me!!!

**Comment by joehni** [comment]
Caused by JDK 1.3 compatibility code ;-)

**Comment by ge0ffrey** [comment]
Thanks, xstream is great :)
