### ISSUE TITLE
class whitelisting inconsistencies

### ISSUE THREAD

**Issue by ar-dia** [x-stream/xstream#39]
I noticed the following inconsistency considering the classes whitelist specification.

When deserializing an object whose class contains Font, String needs to be added additionally to the class whitelist (see e.g. [TextParameters](https://github.com/ar-dia/tests/blob/master/xstream-whitelisting-inconsistency/src/main/java/com/example/xstream/whitelisting/inconsistency/TextParameters.java) and [ClassWhitelistingTest](https://github.com/ar-dia/tests/blob/master/xstream-whitelisting-inconsistency/src/test/java/com/example/xstream/whitelisting/inconsistency/ClassWhitelistingTest.java)).
This made me assume that all classes which are used to build the object would need to be whitelisted (if String needs to be whitelisted then, I thought, you would need to whitelist other classes as well).
This is however not the case which I found out only lately and was surprised by (because I then thought that whitelisting would not work correctly). E.g. it's not the case when String is used directly in one of custom classes (see [StringWrapper](https://github.com/ar-dia/tests/blob/master/xstream-whitelisting-inconsistency/src/main/java/com/example/xstream/whitelisting/inconsistency/StringWrapper.java) and testDeserializationWithoutStringInAllowTypesButNoFont()), but I needed some time to find that out.

Perhaps one should document (on http://x-stream.github.io/security.html) that:
- only the outer-most classes need to be whitelisted and
- only in case some special classes are used (e.g. Font), one needs to additionally whitelist String.
 (Or alternatively one could make FontConverter trust String by default?)

**Comment by joehni** [comment]
The XStream security framework is used for protection against a manipulated XML data. The rules apply only if XStream is responsible for loading a class. This is always the case for the type representing the root object. However, it's the JDK runtime itself that loads all the classes for its member fields. As long as a child element matches exactly the serialized type, there's no reason for XStream to apply any security rules. Change the type of StringWrapper.stringValue to Object and you'll see that XStream creates a class attribute on its own at serialization time and that it will check the rules before it deserializes the member.

This is also the reason why the font attributes are checked: The Font implementation keeps all attributes in a map that might contain all sort of types.

Additionally the rules are only applied if the converter implementation actually uses XStream to resolve the type name from the XML to a class type. If someone writes a converter that instantiates arbitrary classes on its own, its in the responsibility of that converter's author to protect his users.

**Comment by ar-dia** [comment]
Ah, now I understand why it happens. I did not expect that it is due to the way how Font class serializes itself, i.e. that it is using a collection inside it for (de)serialization.
It's clear that for collections (de)serialization (I tried `List<SomeAbstractType>`), the collection type itself and the concrete types inside the collection would need to be whitelisted.

**Comment by biergit** [comment]
I was wondering the same so I think extending the documentation might be worth it.

**Comment by joehni** [comment]
I've added an additional hint to the documentation. Thanks for the suggestion.
