### ISSUE TITLE
Unmarshalled Throwable's do not allow to add suppressed exceptions

### ISSUE THREAD

**Issue by DidierLoiseau** [x-stream/xstream#4]
When xstream marshals a Throwable without suppressed exceptions, it keeps the `suppressedExceptions` collection as-is (i.e. it is the `SUPPRESSED_SENTINEL`). When it later unmarshals it, it results in a new instance of the unmodifiable collection behind it.

However, since it is not the `SUPPRESSED_SENTINEL` instance, `addSuppressed()` does not replace it with an `ArrayList`. By consequent, trying to add a new suppressed exception throws an `UnsupportedOperationException`:

```
java.lang.UnsupportedOperationException
    at java.util.Collections$UnmodifiableCollection.add(Collections.java:1075)
    at java.lang.Throwable.addSuppressed(Throwable.java:1054)
…
```

I agree that one could argue that this is a bug in `addSuppressed`. Nevertheless, the implementation of `Throwable.readObject()` explicitly replaces the `suppressedExceptions` with `SUPPRESSED_SENTINEL` if it is an empty list.

Tested with xstream 1.4.8 on Oracle JDK 1.7.0_72-b14.

**Comment by joehni** [comment]
Thanks for head-sup. Actually XStream lacks support for suppressedExceptions at all currently, but it should at least initialize all fields properly.

**Comment by DidierLoiseau** [comment]
What do you mean by lacking support for suppressedExceptions? I think proper initialization of the fields would be sufficient, wouldn't it?

BTW if you want to remain compatible with java ≤ 6, you should probably ignore the `suppressedExceptions` when the field does not exist. Last year when we migrated to java 7, we had to do the migration of the whole environment simultaneously because the java 6 clients could not unmarshal exceptions thrown by java 7 servers.

**Comment by joehni** [comment]
Suppressed exceptions are currently not exported at all. XStream usually supports all elements of an object and decides on the current runtime what to do. That was already the case for the Stack trace elements of Throwables, introduced with Java 1.4 although XStream still supported 1.3.

**Comment by dmurat** [comment]
I apologize for this unpopular question, but is there any chance for XStream 1.5 (including this fix) to be released any time soon?
