### ISSUE TITLE
Custom converter on a attribut field

### ISSUE THREAD

**Issue by chrisschauer** [x-stream/xstream#40]
Hi,
i know this topic was often discussed in the past. But i never read a reliable answer.
I really appreciate a solution where i can use a custom converter on a attribute field.

Is there any possibility? 

Here a test snippet - The method canConvert() is called. But marsahl() or unmarshal() is never called.

```
public class XmlTests {
    private String xml =
            "<car para1=\"value1\" para2=\"value2\">\n" +
            "    <another>what</another>\n" +
            "</car>";

    @Test
    public void testXStream() throws Exception {
        XStream xStream = new XStream(new StaxDriver());
        xStream.ignoreUnknownElements();

        // register a converter
        xStream.registerConverter(new MyEnumConverter());
        System.out.println(xStream.getConverterLookup().lookupConverterForType(MyEnum.class));

        xStream.processAnnotations(MyDTO.class);
        MyDTO dto = (MyDTO) xStream.fromXML(xml);
    }

    @XStreamAlias("car")
    public class MyDTO {

        @XStreamAlias("para1")
        @XStreamAsAttribute
        private MyEnum foo;

        @XStreamAlias("para2")
        @XStreamAsAttribute
        private String bar;
    }

    public enum MyEnum {
        VALUE1,
        VALUE2
    }

    public class MyEnumConverter implements Converter {

        @Override
        public void marshal(Object source, HierarchicalStreamWriter writer, MarshallingContext context) {
        }

        @Override
        public Object unmarshal(HierarchicalStreamReader reader, UnmarshallingContext context) {
            return null;
        }

        @Override
        public boolean canConvert(Class type) {
            return type.isEnum();
        }
    }
}
```

**Comment by joehni** [comment]
This is explained in the [converter tutorial](http://x-stream.github.io/converter-tutorial.html#SingleValueConverter) as well as in the [alias tutorial](http://x-stream.github.io/alias-tutorial.html#attributes). You need a SingleValueConverter to verify that the converter represents a type in one single string.

**Comment by chrisschauer** [comment]
Ahh o.k. Thanks for the tutorial links.

The reason for the question was a generic converter i wrote for converting enums.
I missed the feature, where i can specifiy a string value for an enum constant. E.g. value "myenum" will return Enum.MYVALUE 

For this i invented 2 Annotations: **@XStreamEnum** and **@XStreamEnumValue**
A enum now looks like: 

```
@XStreamEnum
public enum ApplianceType {

    @XStreamEnumValue("thermostat")
    THERMOSTAT,

    @XStreamEnumValue("heater_central")
    HEATER
}
```

With my generic enum converter i haven't to write a converter for every enum. Here is the unmarshal method:


```    
@Override
    public Object unmarshal(HierarchicalStreamReader reader, UnmarshallingContext context) {
        Class enumType = context.getRequiredType();

        // for all enum values
        for (Field enumValue : enumType.getDeclaredFields()) {
            if (enumValue.isAnnotationPresent(XStreamEnumValue.class)) {
                XStreamEnumValue annotation = enumValue.getAnnotation(XStreamEnumValue.class);

                // found annotation and xml value match with annotation value
                if (annotation.value().equals(reader.getValue())) {
                    return Enum.valueOf((Class<Enum>) enumValue.getType(), enumValue.getName());
                }
            }
        }
        return null;
    }
```

It works great, except for attributs. I know i have to use a SingleValueConverter, but is there a chance to get the required type of the Enum?

If you want, i could extend the existing EnumSingleValueConverter. The default behavior could be searching for the exact enum constant, or if the annotation is present use the custom mapping with annotation.value().

Thx

**Comment by joehni** [comment]
XStream has already a similar functionality with the EnumToStringConverter. Since each instance is registered explicitly for an Enum type, it does know the required type. If you drop your XStreamEnum annotation and use XStreamConverter to register your converter instead, you have the same effect.

**Comment by chrisschauer** [comment]
The EnumToStringConverter works fine with a given map for enum's string representation. But i have 20-25 Enums. Do i have to create for every enum a converter with a map and register it like that:

```
xStream.registerConverter(new EnumToStringConverter<>(MyEnum.class, map));
```

My proposed annotation makes a map obsolete, because the enum constant is annotated with the string representation. Additionally definition of string represenation and enum constant is on same location. See enum ApplianceType on my previous post.

**Comment by joehni** [comment]
You will have to register a converter instance for every Enum type in any case. You implement an appropriate toString implementation instead of a map, e.g.

    @XStreamConverter(EnumToStringConverter.class)
    public enum Color {
        RED, GREEN, BLUE;
        private final static EnumMap<Color, String> strings;
    
        static {
            strings = new EnumMap<>(Color.class);
            strings.put(RED, "red");
            strings.put(GREEN, "green");
            strings.put(BLUE, "blue");
        }
    
        @Override
        public String toString() {
            return strings.get(this);
        };
    }

It simply depends on your use case. If you're satisfied with your solution using these annotations, it's fine. You might even do this:

    @XStreamConverter(EnumToStringConverter.class)
    public enum Color {
        @XStreamEnumValue("red")
        RED, 
        @XStreamEnumValue("green")
        GREEN, 
        @XStreamEnumValue("blue")
        BLUE;
    
        @Override
        public String toString() {
            return this.getClass().getAnnotation(XStreamEnumValue.class).value();
        };
    }

However, XStream itself processes annotations in the AnnotationMapper alone, core converters will not look for annotations.

**Comment by chrisschauer** [comment]
O.k. i have understood, i can't register a global converter for all enums. I didn't know the way to override the toString()-Method.

Thank you a lot for your time and perfect support.
