### ISSUE TITLE
Null valueFieldName for ToAttributedValueConverter with annotation XStreamConverter

### ISSUE THREAD

**Issue by QIvan** [x-stream/xstream#41]
Hi! I try to marshall class 
```java
    @AllArgsConstructor
    @XStreamAlias(value = "message")
    class RendezvousMessage {
        private int messageType;
        private String content;
    }
```

with __ToAttributedValueConverter__ to next xml representation: 
```xml
<message messageType="1" content="test"/>
```

If I init converter manualy: 
```java 
XStream xStream = new XStream();
Converter converter = new ToAttributedValueConverter(RendezvousMessage.class,
xStream.getMapper(), xStream.getReflectionProvider(), xStream.getConverterLookup(), null);
xStream.registerConverter(converter);

RendezvousMessage msg = new RendezvousMessage(1, "test");
System.out.println(xStream.toXML(msg));
```

it works fine, but if I try init converter with annotation _@XStreamConverter_ 
```java 
    @XStreamConverter(value = ToAttributedValueConverter.class)
    @AllArgsConstructor
    @XStreamAlias(value = "message")
    static class RendezvousMessage {
        private int messageType;
        private String content;
    }
```

I get exeption
```
com.thoughtworks.xstream.InitializationException: Cannot instantiate converter com.thoughtworks.xstream.converters.extended.ToAttributedValueConverter for type ru.open.haven.risk.model.forts.FutSeriesTest$RendezvousMessage : Cannot construct com.thoughtworks.xstream.converters.extended.ToAttributedValueConverter, none of the dependencies match any constructor's parameters

	at com.thoughtworks.xstream.mapper.AnnotationMapper.cacheConverter(AnnotationMapper.java:542)
	at com.thoughtworks.xstream.mapper.AnnotationMapper.processConverterAnnotations(AnnotationMapper.java:300)
	at com.thoughtworks.xstream.mapper.AnnotationMapper.processTypes(AnnotationMapper.java:194)
	at com.thoughtworks.xstream.mapper.AnnotationMapper.processAnnotations(AnnotationMapper.java:174)
	at com.thoughtworks.xstream.mapper.AnnotationMapper.serializedClass(AnnotationMapper.java:125)
	at com.thoughtworks.xstream.mapper.MapperWrapper.serializedClass(MapperWrapper.java:26)
	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:80)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1022)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1011)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:984)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:971)
```

What did I do wrong? 
Thanks!

**Comment by joehni** [comment]
Nothing, it's currently simply not possible. All constructors of ToAttributedValueConverter require a String parameter even if its value is simply null. Therefore you could have declared

    @XStreamConverter(value = ToAttributedValueConverter.class, strings={"messageType"})

However, it is not possible to declare

    @XStreamConverter(value = ToAttributedValueConverter.class, strings={null})

So either we add another constructor that omits the `valueFielName` argument or we enhance the XStreamConverter annotation for an array with typed null values:

    @XStreamConverter(value = ToAttributedValueConverter.class, nulls={String.class})

Or we do both ;-)

In the meantime you could simply derive from ToAttributedValueConverter (e.g. AllAttributesConverter) and add the missing constructor yourself.

**Comment by QIvan** [comment]
Thank you a lot! 

> In the meantime you could simply derive from ToAttributedValueConverter (e.g. AllAttributesConverter) and add the missing constructor yourself.

Yeap, I use exactly this way now  =)

**Comment by joehni** [comment]
Thanks for the PR, but I had it already done locally.

**Comment by QIvan** [comment]
@joehni thank you! But what about failed test? Is it another bug?

**Comment by QIvan** [comment]
And one more question please: when will a release be with this commit?

**Comment by joehni** [comment]
As soon as possible. The current changes should have been released months ago.
