### ISSUE TITLE
ConverterMatcher.canConvert's return value isn't documented

### ISSUE THREAD

**Issue by krichter722** [x-stream/xstream#46]
It's crucial to get any idea how to use `ConverterMatcher.canConvert` from javadoc. If that's documented somewhere else, add a link in javadoc.

experienced with 022242e

**Comment by joehni** [comment]
> Determines whether the converter can marshall a particular type.
The method's name is formulated as a parameterized question, the return value is boolean ;-)

**Comment by krichter722** [comment]
> The method's name is formulated as a parameterized question, the return value is boolean ;-)

And when is it `true` and when is it `false`?

**Comment by joehni** [comment]
Seriously? `true` if you can convert, `false` otherwise

**Comment by krichter722** [comment]
> Seriously? 

Yes, several versions are buggy and seem to work the opposite way. That's why useful interface specification is necessary. Pity, that you don't seem to be collaborative - would have love to file those bugs.

**Comment by joehni** [comment]
> Yes, several versions are buggy and seem to work the opposite way.

Prove it. XStream has extensive unit tests.

> Pity, that you don't seem to be collaborative

If you report hairsplitting issues? Sorry, but I have to assume that you know well enough, what this method is about, there's hardly a misinterpretation possible.

> would have love to file those bugs

See, if you had reported first some real issues, where something went wrong, because of an ambiguous description, then you would have all reason to point at the javadoc.

**Comment by krichter722** [comment]
> I have to assume that you know well enough, what this method is about, there's hardly a misinterpretation possible.

That contradictory. Either there's no misinterpretation possible, then you don't have to assume anything and can rely on your well made documentation. If you have to assume anything in software development changes are there's something wrong or incomplete...

> See, if you had reported first some real issues, where something went wrong, because of an ambiguous description, then you would have all reason to point at the javadoc.

That's not how issue reports against documentation work.
