### ISSUE TITLE
Improve documentation of HierarchicalStreamReader.getAttribute

### ISSUE THREAD

**Issue by krichter722** [x-stream/xstream#47]
`HierarchicalStreamReader.getAttribute(String)` doesn't explain what happens if the attribute isn't specified (is `null` returned? expection thrown?).

experienced with 1.4.9

**Comment by joehni** [comment]
It acts like a Map, it returns null.

**Comment by krichter722** [comment]
> It acts like a Map, it returns null.

I know, are you planning to fix this issue?

**Comment by joehni** [comment]
Labels and milestones are not just for fun.

**Comment by krichter722** [comment]
> Labels and milestones are not just for fun.

Right, sorry.
