### ISSUE TITLE
JavaBeanConverter can't serialize null values when the property's default value is non-null

### ISSUE THREAD

**Issue by rkreis** [x-stream/xstream#5]
As far as I can see, XStream has no way of representing `null` values (although often requested). While this is no problem for fields with a default value of `null`, or when the initialization is skipped, it makes `JavaBeanConverter` fail in simple cases like the following:
[Test case where a bean can not be serialized and then deserialized correctly] (https://gist.github.com/anonymous/32360b384968f8734754) (`TestBeanConverter.testNullValue` fails while all other tests pass)

[My current workaround] (https://code.google.com/p/jasima/source/browse/trunk/jasima_gui/src/jasima_gui/PermissiveBeanConverter.java#69) is adding an `is-null` attribute to properties that are `null` . It would be nice to accomplish this without breaking XStream compatibility.

**Comment by joehni** [comment]
What works is this:
```java
    public static class ExplicitlyInitialized {
        private Integer i = new Integer(3);
        private String s = "test";

        public Integer getValue() {
            return this.i;
        }

        public void setValue(Integer value) {
            this.i = value;
        }
        
        public String getString() {
            return s;
        }
        
        public void setString(String s) {
            this.s = s;
        }
    }

    public void testExplicitNullValue() {
        XStream xstream = new XStream();
        xstream.registerConverter(
            new JavaBeanConverter(xstream.getMapper()), XStream.PRIORITY_LOW);
        String input = ""
            + "<explicit>\n"
            + "  <value class=\"null\"/>\n"
            + "</explicit>";
        xstream.alias("explicit", ExplicitlyInitialized.class);

        ExplicitlyInitialized explicit = (ExplicitlyInitialized)xstream.fromXML(input);
        assertNull(explicit.getValue());
        assertEquals("test", explicit.getString());
    }
```
But this only demonstrated that it is already possible to deserialize a null value. As long as the JavaBeanConverter does omit tags for null values when marshalling, it is not of great help. Thanks for heads-up.

**Comment by rkreis** [comment]
That's already very helpful, as it enables me to keep my output compatible to plain XStream.

Should I modify `JavaBeanConverter` and open a PR?

**Comment by joehni** [comment]
Yes, please, PR is welcome. We're still busy saving all our projects from Codehaus ...

**Comment by shybbq** [comment]
nice thank y
