### ISSUE TITLE
Issue with saving/reloading Field with "unregular" characters

### ISSUE THREAD

**Issue by pmouawad** [x-stream/xstream#51]
[testcase-src.zip](https://github.com/x-stream/xstream/files/219929/testcase-src.zip)
Hello,
We have an issue on Apache JMeter when switching from XppDriver to StaxDriver with XStream as per:

- http://x-stream.github.io/tutorial.html#init

I attach a test case showing the problem.
I don't know if it's a StaxDriver bug or XStream one.

Thanks

**Comment by joehni** [comment]
Hi,

well, your source code already contains invalid UTF-8 characters (assuming your Java files are UTF-8 encoded). This means that already the compiler produces garbage when creating the class file.

However, not every character is valid in XML (and it depends on the XML version). Some parsers do not care (like Xpp3), some do (all StAX) drivers. See valid characters in [XML spec 1.0](http://www.w3.org/TR/2006/REC-xml-20060816/#charsets) and [XML spec 1.1](http://www.w3.org/TR/2006/REC-xml11-20060816/#charsets), and XStream's [FAQ](http://x-stream.github.io/faq.html#XML_null_char).

**Comment by pmouawad** [comment]
Thanks a lot Jörg ! You rock.
Shall I close this ?
Thanks

**Comment by joehni** [comment]
Done :)
