### ISSUE TITLE
set Id property - identity reference

### ISSUE THREAD

**Issue by decoursin** [x-stream/xstream#55]
I'd like to manually set the id property, when using identity reference. It doesn't seem like this is possible?

**Comment by joehni** [comment]
You can provide your own implementation for the ID generator. The implementation is a constructor argument for the ReferenceByIdMarshaller used by the ReferenceByIdMarshallingStrategy. XStream.setMode is simply a selector for a predefined MarshallingStrategy activated by calling XStream.setMarshallingStrategy. See acceptance test for an example: https://github.com/x-stream/xstream/blob/master/xstream/src/test/com/thoughtworks/acceptance/BeanIDCircularReferenceTest.java

**Comment by decoursin** [comment]
I wasn't able to try this, but thank you for the help!
