### ISSUE TITLE
Output xml is not able to replace element name with @XStreamAlias when polymorphism(interface)

### ISSUE THREAD

**Issue by zacyang** [x-stream/xstream#57]
I've encountered a case where I need to out toXml a ojbect, which is an aggregate root of a lot of other objects( in which contains a some implementation of interface).

The following is the test to demonstrate the issue.

* Given I have a interface
`
public interface SomeInterface {
}
`
* And I have an implementation of this interface
`
@XStreamAlias("Child")
public class Child implements SomeInterface {
}
` 

* And I wrap this implementation with an other object
`
@XStreamAlias("Parent")
public class Parent {
    private SomeInterface item;
    public Parent(SomeInterface item) {
        this.item = item;
    }
}
`

* Then when I run this test , it fails:
` public void shouldGetCorrectAliasWhenPoly() throws Exception {
`
`
        String result = xStream.toXML(new Parent(new Child()));    
`
`
        assertThat(result).isEqualTo("<Parent>\n" +
                "  <Child/>\n" +
                "</Parent>");
    }
`

Please let me know if this is an issue or not, and I am more than happy to issue a PR to fix this.

**Comment by joehni** [comment]
Hi,

that's normal. The tag of the inner element is defined by the name of the member field of Parent, i.e. this is "item" in your case. Have a look at the [alias tutorial](http://x-stream.github.io/alias-tutorial.html).
