### ISSUE TITLE
Performance degradation through ImplicitCollectionMapper

### ISSUE THREAD

**Issue by purnhar** [x-stream/xstream#61]
After upgrading from XStream 1.4.8 to 1.4.9 i observed a huge degradation of the performance for XML (un-)marshalling. XStream suddenly got 50-100% slower.
I created a sampling with VisualVM. In my opinion the reason for the perfomance degradation is the new code for the fix "Implicit collection declaration is erroneously inherited or propagated to hidden field of same name." in the class ImplicitCollectionMapper. This fix leads to massive calls to Class.getDeclaredField, which is extremly expensive.

Would it be a possible, to cache the results of the getDeclaredField call or do you have any other idea for a performance optimization? I implemented a caching solution in the pull request #60 .

**Comment by joehni** [comment]
Uses cache of ReflectionProvider now.

**Comment by joehni** [comment]
Applied to v-1,4,x branch and master.
