### ISSUE TITLE
HierarchicalStreamReader.getAttribute(String) don't return value

### ISSUE THREAD

**Issue by zloyreznic** [x-stream/xstream#63]
`XStream st = new XStream(new StaxDriver());`
`<data result="0" new_changestamp="4"></data>`

> XMLData person = new XMLData();
>         person.setResult(reader.getAttribute("result"));
>         int attributeCount = reader.getAttributeCount();
>         String new_changestamp = reader.getAttribute("new_changestamp");
>         person.setTimestamp(new_changestamp);
>         String attribute = reader.getAttribute(0);
>         String attribute1 = reader.getAttribute(1);
>         String attributeName = reader.getAttributeName(0);
>         String attributeName1 = reader.getAttributeName(1);
>         person.setData(reader.getValue());
>         return person;
> ![screenshot_1](https://cloud.githubusercontent.com/assets/3604074/17666247/029a9fde-6308-11e6-9eef-0aafabe61926.png)

 reader.getAttribute("new_changestamp"); = return null

**Comment by joehni** [comment]
See FAQ, what to do when the [unmarshalling fails](http://x-stream.github.io/faq.html#XML_unmarshalling_fails) and what is special about [underscores](http://x-stream.github.io/faq.html#XML_double_underscores).
