### ISSUE TITLE
Infinite loops in HashMap fields of FieldAliasingMapper

### ISSUE THREAD

**Issue by EXPEroistvan** [x-stream/xstream#69]
HashMap can bump into infinite loops if a multi-threaded application runs on multi-core CPU and threads try to put-put or put-get actions simultaneously.
That situation occurred in our application at high-load when omitField method was called up parallelly.

`Thread 71232: (state = IN_JAVA)
- java.util.HashMap.put(java.lang.Object, java.lang.Object) @bci=118, line=494 (Compiled frame; information may be imprecise)
- java.util.HashSet.add(java.lang.Object) @bci=8, line=217 (Compiled frame)
- com.thoughtworks.xstream.mapper.FieldAliasingMapper.omitField(java.lang.Class, java.lang.String) @bci=10, line=77 (Interpreted frame)
- com.thoughtworks.xstream.XStream.omitField(java.lang.Class, java.lang.String) @bci=52, line=1782 (Interpreted frame)
- com.***************.HotelSearch.<init>() @bci=134, line=60 (Interpreted frame)
- sun.reflect.GeneratedConstructorAccessor35.newInstance(java.lang.Object[]) @bci=24 (Interpreted frame)`

`Thread 70994: (state = IN_JAVA)
- java.util.HashMap.put(java.lang.Object, java.lang.Object) @bci=118, line=494 (Compiled frame; information may be imprecise)
- java.util.HashSet.add(java.lang.Object) @bci=8, line=217 (Compiled frame)
- com.thoughtworks.xstream.mapper.FieldAliasingMapper.omitField(java.lang.Class, java.lang.String) @bci=10, line=77 (Interpreted frame)
- com.thoughtworks.xstream.XStream.omitField(java.lang.Class, java.lang.String) @bci=52, line=1782 (Interpreted frame)
- com.***************.bom.HotelSearch.<init>() @bci=134, line=60 (Interpreted frame)
  `

**Comment by joehni** [comment]
Yes. This is to be expected. It is [explicitly](http://x-stream.github.io/faq.html#Scalability_Thread_safety) stated that the configuration part of XStream is *not* thread-safe.
