### ISSUE TITLE
Upgrade Jettison library to latest version

### ISSUE THREAD

**Issue by aaime** [x-stream/xstream#72]
Jettison 1.2 seems to have issues with null values in arrays, a reporter here states the issue has been solved in more recent version, but apparently that requires changes in the xstream code, more info here:

https://osgeo-org.atlassian.net/browse/GEOS-7771

**Comment by joehni** [comment]
Last time I checked, the latest version of Jettison produced much worse effects. They are obvious when running XStream's unit tests. And I reported the problem years ago to Jettison devs using pure StAX API. I'll recheck the latest version from time to time, but I have not much hope. My original it is still open (bug was reported at CodeHaus JIRA, it has been moved to https://github.com/jettison-json/jettison/issues/12).

**Comment by joehni** [comment]
Just made a test with latest version 1.3.8 of Jettison ... not usable for XStream:

Results :

Failed tests: 
  testArrayList(com.thoughtworks.xstream.io.json.JettisonMappedXmlDriverTest)
  testSingletonListWithSimpleObject(com.thoughtworks.xstream.io.json.JettisonMappedXmlDriverTest)
  testListWithSimpleObjects(com.thoughtworks.xstream.io.json.JettisonMappedXmlDriverTest)
  testSingletonListWithComplexObject(com.thoughtworks.xstream.io.json.JettisonMappedXmlDriverTest)
  testListWithComplexNestedObjects(com.thoughtworks.xstream.io.json.JettisonMappedXmlDriverTest)
  testEmbeddedXml(com.thoughtworks.xstream.io.json.JettisonMappedXmlDriverTest)

Tests in error: 
  testEmptyArray(com.thoughtworks.xstream.io.json.JettisonMappedXmlDriverTest)
  testProperties(com.thoughtworks.xstream.io.json.JettisonMappedXmlDriverTest)

**Comment by dkulp** [comment]
Jettison 1.4.1 was just released which contains a new Configuration option to not output the root wrapper element events which can be used to fix these tests.   Path:

```
diff --git a/xstream/src/java/com/thoughtworks/xstream/io/json/JettisonMappedXmlDriver.java b/xstream/src/java/com/thoughtworks/xstream/io/json/JettisonMappedXmlDriver.java
index 803e0702..84bdd5c5 100644
--- a/xstream/src/java/com/thoughtworks/xstream/io/json/JettisonMappedXmlDriver.java
+++ b/xstream/src/java/com/thoughtworks/xstream/io/json/JettisonMappedXmlDriver.java
@@ -76,7 +76,10 @@ public class JettisonMappedXmlDriver extends AbstractDriver {
      * @since 1.4
      */
     public JettisonMappedXmlDriver(Configuration config, final boolean useSerializeAsArray) {
-        config = config == null ? new Configuration() : config;
+        if (config == null) {
+            config = new Configuration();
+            config.setRootElementArrayWrapper(false);
+        }
         mof = new MappedXMLOutputFactory(config);
         mif = new MappedXMLInputFactory(config);
         convention = new MappedNamespaceConvention(config);
```

**Comment by joehni** [comment]
I'll give it a try. Quite in time for 9.4.12 ... ;-)

**Comment by joehni** [comment]
Will go into 1.5.0, Jettison 1.4.1 requires Java 8.
