### ISSUE TITLE
Suggestion - Java 8 time package instead of Joda and Date

### ISSUE THREAD

**Issue by kpopovic** [x-stream/xstream#75]
Hello,
can you support new Java 8 java.time.\* package into http://x-stream.github.io/converters.html.
e.g. OffsetDateTime, ZonedDateTime, MonthDay,...etc...

Best Regards,
Kresimir

**Comment by joehni** [comment]
This issue duplicates [XSTR-774](http://x-stream.github.io/jira/774/).
