### ISSUE TITLE
[Question] Reference object before the object itself

### ISSUE THREAD

**Issue by robertwhitebit** [x-stream/xstream#78]
Hi! :smile_cat: 

Straight to the topic. I have an array of objects where each object refers to another object in the same array. To be more concrete, I have an array (people) with two persons (p1, p2). p1 has a reference to p2 and p2 has a reference to p1. You can find the source code at the end of the description. The xml looks like

```xml
<people id="1">
  <person id="2">
    <name>Adam</name>
    <relative id="3">
      <name>Eve</name>
      <relative reference="2"/>
    </relative>
  </person>
  <person reference="3"/>
</people>
```

The xml is correct but isn't exactly the output I'm looking for. Is it possible to create following output?

```xml
<people id="1">
  <person id="2">
    <name>Adam</name>
    <relative reference="3"/>
  </person>
  <person id="3">
    <name>Eve</name>
    <relative reference="2"/>
  </person>
</people>
```

As you can see, the relative is referenced even though the person is defined later.
My original xml is more complexe. However this way, the xml can be read much more easily and changed (configured) by a human as well.

```java
import com.thoughtworks.xstream.XStream;

public class Reference {

    private static class Person {
        String name;
        Person relative;

        public Person() {
        }

        Person(String name) {
            this.name = name;
        }
    }

    public static void main(String[] args) {
        Person p1 = new Person("Adam");
        Person p2 = new Person("Eve");

        p1.relative = p2;
        p2.relative = p1;

        Person[] people = {p1, p2};

        XStream xstream = new XStream();
        xstream.alias("person", Person.class);
        xstream.alias("people", Person[].class);
        xstream.setMode(XStream.ID_REFERENCES);

        System.out.println(xstream.toXML(people));
    }
}
```

**Comment by robertwhitebit** [comment]
So it's like a Breadth-first "search" instead of Depth-first "search"

**Comment by joehni** [comment]
In short: XStream is based on a real stream model and can therefore not generate forward references.

You'll find a long answer and a possible solution with caveats in a [thread](https://groups.google.com/forum/#!topic/xstream-user/7zuo4EgbYWk) of the user list.

**Comment by robertwhitebit** [comment]
Oh, I see. Thank you very much.
