### ISSUE TITLE
Converting complex data

### ISSUE THREAD

**Issue by Isfirs** [x-stream/xstream#79]
This might not be an issue, more of a way to find a way to implement a converter:

I have data in the format:
```
<root>
    <data>value</data>
    <result>
        <table attr="attr1,attr2,attr3">
            <row attr1="value11" attr2="value12" attr3="value13">
            <row attr1="value21" attr2="value22" attr3="value23">
            <row attr1="value31" attr2="value32" attr3="value33">
            [...]
        </table>
    </result>
</root>
```

How exactly can this be converted by XStream? Components are enough.

**Comment by joehni** [comment]
Start by defining a class containing a data and result member. Continue with a class type for the result and so on. Serialize the instantiated object, so you'll see what XStream generates. You may then tweak XStream's setup to adjust the output. Once you write this XML, you're also able to read it. Look at XStream's tutorials for the different possibilities.
