### ISSUE TITLE
how can i use the new FieldDictionary.java in version 1.4.9？

### ISSUE THREAD

**Issue by cndoublehero** [x-stream/xstream#81]
I have a problem when I'm  using xsteam 1.4.9, a thread block on FieldDictionary:123line when the xstream convert a xml to a object.
https://github.com/x-stream/xstream/blob/master/xstream/src/java/com/thoughtworks/xstream/converters/reflection/FieldDictionary.java
I found the new file change synchronized to a ConcurrentMap and seems it can solve my block issue. Now the problem is how can i use the new FieldDictionary.java in my project? All I can think about is two way:1. create a new FieldDictionary source file in my project and copy the new FieldDictionary content into it;2.compile the new FieldDictionary class file to my private maven repository

any good idea?

**Comment by joehni** [comment]
What do you mean by "thread block"? Do you actually face a dead lock? I wonder, how that might happen, because the only location, where the access to the dictionary is synchronized again, is starting in line 137 and that block is the only location where the dictionary is effectively modified.

**Comment by cndoublehero** [comment]
No, not a dead lock. We found our java logic was very slow at stress testing. I use the "jstack" command to print the java stack and found a lot of thread block on FieldDictionary:123line. After seeing the new FieldDictionary implementation, I copy the new file into my project and do the stress testing again, this time I got a better result.

**Comment by joehni** [comment]
OK. You can use an own implementation (or a private copy of the new version) of a FieldDictionary together with XStream 1.4.9:

``` Java
ReflectionProvider reflectionProvider = JVM.newReflectionProvider(new MyFieldDictionary());
XStream xstream = new XStream(reflectionProvider);
```
