### ISSUE TITLE
Version 1.4.8 and 1.4.9 are built with Java8

### ISSUE THREAD

**Issue by dral3x** [x-stream/xstream#84]
Hi there,

I've just found a big issue.
I'm working on an Android app what is built with Java7.

With those 2 version of xstream library, I've this error
```
Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.
```

Version 1.4.7 works as expected.

I've loaded the library the usual way
```
compile 'com.thoughtworks.xstream:xstream:1.4.9'
```

**Comment by joehni** [comment]
Please see issue  #49

**Comment by dral3x** [comment]
Got it, thanks!

Is there any copy-and-paste solution for this? For example, as you suggest in #49, for telling the annotation processor to ignore those specific files?

**Comment by joehni** [comment]
Unfortunately nobody reported back something like that, so currently it seems the only possible solution to manipulate the final jar or to build it on your own with JDK 1.7.

**Comment by joehni** [comment]
Since XStream 1.4.10 an additional artifact of version 1.4.10-java7 exists in the central Maven repository.
