### ISSUE TITLE
How to compile advanced rowset xml?

### ISSUE THREAD

**Issue by Isfirs** [x-stream/xstream#87]
Hey guys, I don't know where else to put this, so I do it here. Please tell me where I should post this instead to get help if you won't answer it.

I have an advanced xml structure off a table like so:

```
<root>
    <result>
        <rowset key="keyField" columns="keyField, field1, field2, field3">
            <row keyField="" field1="" field2="" field3="" />
        <rowset>
    </result>
</root>
```

How do I have to map this? Do I have to inject a custom converter somehow? 
I would like to map the columns to a specific `Row` class, having each column as field.

i haven't used this library for deep xml structures before, so I am kinda stuck and can't get a clue.

Please help me :cry:

**Comment by joehni** [comment]
For starters: Always go the way Java to XML first. Create your objects, marshal them to XML and compare the output with the format you want to read. Tweak the output until it matches with the input. They you're normally able to read the XML also. Look at the tutorials on XStream's [web site](https://x-stream.github.io/tutorial.html).

**Comment by Isfirs** [comment]
Thank you.

Honestly, I didn't think about tackling it like that!
