### ISSUE TITLE
jackOptions  must be  added?

### ISSUE THREAD

**Issue by IT-crackpot** [x-stream/xstream#92]
Hi 
Can I not use jackOptions?

**Comment by joehni** [comment]
Sorry, I don't understand the question.

**Comment by IT-crackpot** [comment]
![image](https://user-images.githubusercontent.com/14144748/27326692-c0001c1a-55de-11e7-93d9-b4f6cde24b0f.png)
I must open after added this library ,But I not want open

**Comment by joehni** [comment]
Sorry, I have not the slightest clue, what you're talking about and how this should be related to XStream at all.

**Comment by joehni** [comment]
wrong project
