### ISSUE TITLE
java7 artifact breaks with android unit tests when JVM is 8

### ISSUE THREAD

**Issue by dral3x** [x-stream/xstream#95]
Hi there,
Thanks for this great library!

I'm using it on an Android app, built with Java 7.
In the `build.gradle` I've specified the source and target compatibility to 1.7
```
compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_7
    targetCompatibility JavaVersion.VERSION_1_7
}
```
and also loading the `java7` artifact version of this library.
```
compile ('com.thoughtworks.xstream:xstream:1.4.10-java7') {
    exclude group: 'xmlpull'
}
```

It works great for the app but it breaks on unit tests. I'm testing that I configured the library correctly and some xml sample files are parsed correctly.

It crashes while creating an instance of `XStream`, with this error
`com.thoughtworks.xstream.InitializationException: Could not instantiate mapper : com.thoughtworks.xstream.mapper.LambdaMapper`

The reason is that on my machine Java is 1.8 version and so the following code inside `XStream.java` passed and `LambdaMapper` class is loaded.
```
if (JVM.is18()) {
    mapper = buildMapperDynamically("com.thoughtworks.xstream.mapper.LambdaMapper", 
        new Class[]{Mapper.class}, new Object[]{mapper});
}
```
`LambaMapper` does not exist because, on the artifact I'm loading, that class is correctly not present.
If I load the plain version `compile 'com.thoughtworks.xstream:xstream:1.4.10'` the initializer succeed and the tests passes.

I think a fix could be let the `buildMapperDynamically` fails, logging the error message but don't let crash the process. Basically adding a `try / catch` around that invocation.

What do you think?
Thanks!

**Comment by joehni** [comment]
XStream can actually run even on Java 1.4. The only difference is that the -java7 artifact lacks any class compiled for Java 8 for environments that support Java 7, but try to access/load nevertheless any class file in a Java archive whether it is used by the application or not.

**Comment by dral3x** [comment]
I understand your explanation, makes sense.

The problem is that it tries to load classes based on the JVM used, not the actual version of the `x-stream` library.
That's why I was asking to add a try/catch around this
```
mapper = buildMapperDynamically("com.thoughtworks.xstream.mapper.LambdaMapper", 
        new Class[]{Mapper.class}, new Object[]{mapper});
```
The `LambdaMapper` class should be loaded *ONLY* when compiling with JVM 1.8 *AND* that class is available in the library. Otherwise it will crash by loading something it should not even try to load.

A `try/catch` will be the easiest way to address this issue. Not perfect, but working.
If you want I can make a pull request for that.
Let me know. Thank you!

**Comment by joehni** [comment]
See, the 1.4.10-jdk7 artifact is not meant to be run on a Java 8 runtime. It is not even meant for a standard Java 7 runtime. It has been published only as convenience variant for any Java 7 runtime, that insists to process all classes of a library independently of their usage at runtime (Android is the most prominent environment with such a behaviour). The build process simply omits those classes then.

Note, that there are a lot more classes normally available for Java 8 that are ignored in a Java 7 environment. Since you can build also 1.4.10-java6/5/4 artifacts (the latter for old Android versions), you would have to wrap in a lot more cases.

What you might do as alternative for your unit test: Set the system property java.specification.version to 1.7. I suppose, Gradle uses also the Surefire plugin and that one can be configured for individual system properties for the test run. At least from the command line you can fake the version for XStream:

```
$ java -showversion -Djava.specification.version=1.7 -cp xstream-1.4.10.jar com.thoughtworks.xstream.core.JVM
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

XStream JVM diagnostics
java.specification.version: 1.7
java.specification.vendor: Oracle Corporation
java.specification.name: Java Platform API Specification
java.vm.vendor: Oracle Corporation
java.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
Version: 1.7
XStream support for enhanced Mode: true
XStream support for reduced Mode: true
Supports AWT: true
Supports Swing: true
Supports SQL: true
Java Beans EventHandler present: true
Standard StAX XMLInputFactory: com.sun.xml.internal.stream.XMLInputFactoryImpl
Standard StAX XMLOutputFactory: com.sun.xml.internal.stream.XMLOutputFactoryImpl
Optimized TreeSet.addAll: true
Optimized TreeMap.putAll: true
Can parse UTC date format: true
Can create derive ObjectOutputStream: true
Reverse field order detected for JDK: false
Reverse field order detected (only if JVM class itself has been compiled): false
```

**Comment by dral3x** [comment]
Thank you @joehni !

Adding `-Djava.specification.version=1.7` to the VM options (in the test configuration) make it work correctly.
